"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, ClipboardList, PackageCheck, Power, Store, Truck } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Card, EmptyState, FormField, OrderSummary, StatusBadge, formControlClassName } from "@/components/ui";
import { operatorOperationsRepository } from "@/data";
import { SubmitButton } from "@/features/auth/auth-controls";
import { OPERATOR_ID, OperationsLoading, OperatorOrderList, PageHeading, actionClassName, formatDate, secondaryActionClassName, statusTone, titleCase } from "@/features/operator-operations/operations-ui";
import { formatMoney } from "@/lib/money";

const active = ["CONFIRMED", "ACCEPTED", "PREPARING", "READY", "OUT_FOR_DELIVERY"];
const nextLabel: Record<string, string> = { CONFIRMED: "Accept order", ACCEPTED: "Start preparing", PREPARING: "Mark ready to leave", READY: "Complete pickup" };

export function OperatorDashboardScreen() {
  const query = useQuery({ queryKey: ["operator-dashboard", OPERATOR_ID], queryFn: () => operatorOperationsRepository.dashboard(OPERATOR_ID) });
  if (query.isLoading) return <OperationsLoading />;
  if (!query.data) return <EmptyState title="Dashboard unavailable" description="The operator business could not be loaded." />;
  const { business, activeOrders, totalOrders, paidRevenue, lowStock, unassigned } = query.data;
  return <div><PageHeading eyebrow={business.name} title="Operations dashboard" description="Run today's handovers, deliveries, and stock from one live workspace." action={<StatusBadge tone={business.isOpen ? "success" : "danger"}>{business.isOpen ? "Open" : "Closed"}</StatusBadge>} /><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Active orders", activeOrders.length],["Paid order value",formatMoney(paidRevenue)],["Delivery assignments",unassigned],["Low-stock lines",lowStock]].map(([label,value]) => <Card key={label} className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></Card>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3"><Link href="/operator/status" className={`${secondaryActionClassName} justify-between`}>Trading status <Store className="size-4" /></Link><Link href="/operator/redeem" className={`${actionClassName} justify-between`}>Redeem a code <PackageCheck className="size-4" /></Link><Link href="/operator/stock/order" className={`${secondaryActionClassName} justify-between`}>Receive stock <ArrowRight className="size-4" /></Link></div><div className="mt-8 flex items-end justify-between gap-4"><div><h2 className="text-heading-2 font-semibold">Active orders</h2><p className="mt-1 text-sm text-muted-foreground">{totalOrders} orders recorded for this business.</p></div><Link href="/operator/orders" className="text-sm font-semibold text-primary">View all</Link></div><OperatorOrderList orders={activeOrders} empty="No active orders" /></div>;
}

export function TradingStatusScreen() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["operator-dashboard", OPERATOR_ID], queryFn: () => operatorOperationsRepository.dashboard(OPERATOR_ID) });
  const mutation = useMutation({ mutationFn: (isOpen: boolean) => operatorOperationsRepository.setTradingStatus(OPERATOR_ID, isOpen), onSuccess: () => client.invalidateQueries({ queryKey: ["operator-dashboard", OPERATOR_ID] }) });
  if (query.isLoading) return <OperationsLoading count={1} />; if (!query.data) return <EmptyState title="Business unavailable" description="Trading status could not be loaded." />;
  const open = query.data.business.isOpen;
  return <div className="mx-auto max-w-2xl"><PageHeading eyebrow="Availability" title="Trading status" description="Customers can place new orders only while your business is open." /><Card className="mt-7 p-6"><div className="flex items-start justify-between gap-4"><div><Power className={`size-7 ${open ? "text-success" : "text-danger"}`} /><h2 className="mt-4 text-xl font-semibold">{open ? "Open for orders" : "Closed to new orders"}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Active orders stay visible and can still be completed while you are closed.</p></div><StatusBadge tone={open ? "success" : "danger"}>{open ? "Open" : "Closed"}</StatusBadge></div><button type="button" disabled={mutation.isPending} onClick={() => mutation.mutate(!open)} className={`${open ? secondaryActionClassName : actionClassName} mt-6 w-full`}>{mutation.isPending ? "Updating…" : open ? "Close business" : "Open business"}</button>{mutation.isError ? <p role="alert" className="mt-3 text-sm text-danger">{mutation.error.message}</p> : null}</Card></div>;
}

export function OperatorOrdersScreen() {
  const query = useQuery({ queryKey: ["operator-orders", OPERATOR_ID], queryFn: () => operatorOperationsRepository.listOrders(OPERATOR_ID) });
  return <div><PageHeading eyebrow="Fulfilment" title="Orders" description="Manage every paid, active, completed, or cancelled customer request." />{query.isLoading ? <OperationsLoading /> : <OperatorOrderList orders={query.data ?? []} />}</div>;
}

export function OperatorOrderDetailScreen({ orderId }: { orderId: string }) {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["operator-order", OPERATOR_ID, orderId], queryFn: () => operatorOperationsRepository.findOrder(OPERATOR_ID, orderId) });
  const mutation = useMutation({ mutationFn: () => operatorOperationsRepository.advanceOrder(OPERATOR_ID, orderId), onSuccess: () => { client.invalidateQueries({ queryKey: ["operator-order", OPERATOR_ID, orderId] }); client.invalidateQueries({ queryKey: ["operator-orders", OPERATOR_ID] }); client.invalidateQueries({ queryKey: ["operator-dashboard", OPERATOR_ID] }); } });
  if (query.isLoading) return <OperationsLoading />; if (!query.data) return <EmptyState icon={ClipboardList} title="Order not found" description="This order does not belong to your business." action={<Link className="font-semibold text-primary" href="/operator/orders">Return to orders</Link>} />;
  const { order, customer, items, delivery, code } = query.data; const canAdvance = Boolean(nextLabel[order.status]) && !(order.status === "READY" && order.fulfilmentMode === "DELIVERY");
  return <div><Link href="/operator/orders" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4" /> Orders</Link><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex gap-2"><span className="font-mono text-sm font-semibold">{order.orderNumber}</span><StatusBadge tone={statusTone(order.status)}>{titleCase(order.status)}</StatusBadge></div><h1 className="mt-3 text-heading-1 font-semibold">{customer ? `${customer.firstName} ${customer.lastName}` : "Customer order"}</h1><p className="mt-2 text-sm text-muted-foreground">Placed {formatDate(order.createdAt, true)}</p></div><div className="flex flex-wrap gap-3">{order.fulfilmentMode === "DELIVERY" && active.includes(order.status) ? <Link href={`/operator/orders/${order.id}/assign`} className={secondaryActionClassName}><Truck className="size-4" /> Assign delivery</Link> : null}{code?.status === "ACTIVE" ? <Link href={`/operator/redeem/${order.id}`} className={actionClassName}>Redeem</Link> : null}</div></div><div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]"><OrderSummary businessName={customer ? `${customer.firstName} ${customer.lastName}` : undefined} orderNumber={order.orderNumber} items={items.map((item) => ({ id:item.id,name:item.product?.name ?? "Water product",quantity:item.quantity,unitPrice:item.unitPrice,lineTotal:item.lineTotal }))} subtotal={order.subtotal} deliveryFee={order.deliveryFee} depositAmount={order.depositAmount} discount={order.discount} total={order.total} /><div className="space-y-4"><Card className="p-5"><h2 className="font-semibold">Fulfilment</h2><p className="mt-2 text-sm text-muted-foreground">{titleCase(order.fulfilmentMode)}</p>{delivery?.assignedToName ? <p className="mt-3 text-sm"><strong>{delivery.assignedToName}</strong><br /><span className="text-muted-foreground">{delivery.assignedToPhone} · {delivery.etaMinutes} min ETA</span></p> : <p className="mt-3 text-sm text-warning">No delivery partner assigned</p>}</Card>{canAdvance ? <button type="button" onClick={() => mutation.mutate()} disabled={mutation.isPending} className={`${actionClassName} w-full`}>{mutation.isPending ? "Updating…" : nextLabel[order.status]} <ArrowRight className="size-4" /></button> : null}{mutation.isError ? <p role="alert" className="text-sm text-danger">{mutation.error.message}</p> : null}</div></div></div>;
}

export function AssignOrderScreen({ orderId, returnTo = "order" }: { orderId: string; returnTo?: "order" | "redemption" }) {
  const router = useRouter(); const client = useQueryClient(); const query = useQuery({ queryKey: ["operator-order", OPERATOR_ID, orderId], queryFn: () => operatorOperationsRepository.findOrder(OPERATOR_ID, orderId) }); const [error, setError] = useState("");
  const mutation = useMutation({ mutationFn: (input: { name:string;phone:string;etaMinutes:number }) => operatorOperationsRepository.assignDelivery(OPERATOR_ID, orderId, input), onSuccess: () => { client.invalidateQueries({ queryKey: ["operator-order", OPERATOR_ID, orderId] }); router.push(returnTo === "redemption" ? `/operator/redeem/assigned?orderId=${orderId}` : `/operator/orders/${orderId}`); } });
  if (query.isLoading) return <OperationsLoading count={1} />; if (!query.data) return <EmptyState title="Order not found" description="Delivery assignment is unavailable." />;
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const input = { name:String(data.get("name") ?? ""), phone:String(data.get("phone") ?? ""), etaMinutes:Number(data.get("eta")) }; if (input.name.trim().length < 2 || input.phone.trim().length < 7) { setError("Enter a valid name and phone number."); return; } setError(""); mutation.mutate(input); }
  return <div className="mx-auto max-w-xl"><PageHeading eyebrow={query.data.order.orderNumber} title="Assign delivery" description="Add the person handling this order and a realistic arrival estimate." /><form onSubmit={submit} className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="assign-name" label="Delivery partner name" required disabled={mutation.isPending}>{(props) => <input {...props} name="name" defaultValue={query.data?.delivery?.assignedToName} className={formControlClassName} />}</FormField><FormField id="assign-phone" label="Phone number" required disabled={mutation.isPending}>{(props) => <input {...props} name="phone" type="tel" defaultValue={query.data?.delivery?.assignedToPhone} className={formControlClassName} />}</FormField><FormField id="assign-eta" label="ETA in minutes" required disabled={mutation.isPending}>{(props) => <input {...props} name="eta" type="number" min="5" max="240" defaultValue={query.data?.delivery?.etaMinutes ?? 30} className={formControlClassName} />}</FormField>{error ? <p role="alert" className="text-sm text-danger">{error}</p> : null}{mutation.isError ? <p role="alert" className="text-sm text-danger">{mutation.error.message}</p> : null}<SubmitButton pending={mutation.isPending}><Truck className="size-4" /> Save assignment</SubmitButton></form></div>;
}
