"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CheckCircle2, History, PackageCheck, ScanLine } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Card, EmptyState, FormField, StatusBadge, formControlClassName } from "@/components/ui";
import { operatorOperationsRepository } from "@/data";
import { SubmitButton } from "@/features/auth/auth-controls";
import { OPERATOR_ID, OperationsLoading, PageHeading, actionClassName, formatDate, secondaryActionClassName, statusTone, titleCase } from "@/features/operator-operations/operations-ui";

export function RedemptionLookupScreen() {
  const router = useRouter(); const [code, setCode] = useState(""); const [error, setError] = useState("");
  const mutation = useMutation({ mutationFn: () => operatorOperationsRepository.findRedemption(OPERATOR_ID, code), onSuccess: (result) => router.push(`/operator/redeem/${result.order.id}`) });
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!/^\d{6}$/.test(code)) { setError("Enter the customer's 6-digit code."); return; } setError(""); mutation.mutate(); }
  return <div className="mx-auto max-w-xl"><PageHeading eyebrow="Customer handover" title="Redeem confirmation code" description="Verify the customer's six-digit code before releasing a pickup or completing delivery." /><form onSubmit={submit} className="mt-7 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="redeem-code" label="Confirmation code" error={error} required disabled={mutation.isPending}>{(props) => <input {...props} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000" className={`${formControlClassName} text-center font-mono text-2xl tracking-[0.35em]`} />}</FormField>{mutation.isError ? <p role="alert" className="mt-4 text-sm text-danger">{mutation.error.message}</p> : null}<SubmitButton pending={mutation.isPending} className="mt-5"><ScanLine className="size-4" /> Find order</SubmitButton></form></div>;
}

export function RedemptionDetailScreen({ orderId }: { orderId: string }) {
  const router = useRouter(); const client = useQueryClient(); const query = useQuery({ queryKey: ["operator-order", OPERATOR_ID, orderId], queryFn: () => operatorOperationsRepository.findOrder(OPERATOR_ID, orderId) });
  const mutation = useMutation({ mutationFn: () => operatorOperationsRepository.redeem(OPERATOR_ID, orderId, query.data?.code?.displayCode ?? ""), onSuccess: () => { ["operator-order","operator-orders","operator-dashboard","operator-stock","operator-deliveries","customer-order","customer-orders","customer-code","customer-codes","customer-notifications","admin-operations-orders","admin-dashboard"].forEach((key) => client.invalidateQueries({ queryKey: [key] })); router.push(`/operator/redeem/success?orderId=${orderId}`); } });
  if (query.isLoading) return <OperationsLoading />; if (!query.data || !query.data.code) return <EmptyState title="Redemption unavailable" description="No confirmation code is linked to this order." />;
  const { order, customer, items, code, delivery } = query.data;
  return <div className="mx-auto max-w-2xl"><Link href="/operator/redeem" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4" /> New lookup</Link><PageHeading eyebrow={order.orderNumber} title="Confirm handover" description="Check the customer, containers, and assignment before completing this order." /><Card className="mt-7 p-6"><div className="flex justify-between gap-4"><div><p className="text-sm text-muted-foreground">Customer</p><p className="mt-1 font-semibold">{customer ? `${customer.firstName} ${customer.lastName}` : "Customer"}</p></div><StatusBadge tone={statusTone(code.status)}>{titleCase(code.status)}</StatusBadge></div><div className="mt-5 border-t border-border pt-5"><p className="text-sm text-muted-foreground">Products and returns</p>{items.map((item) => <div key={item.id} className="mt-3 flex justify-between gap-4 text-sm"><span>{item.quantity} × {item.product?.name}</span><span className="text-muted-foreground">{item.expectedEmptyReturns} empty return(s)</span></div>)}</div><p className="mt-5 rounded-control bg-surface-muted p-4 text-sm">Code <strong className="font-mono text-lg tracking-widest">{code.displayCode}</strong></p>{delivery?.assignedToName ? <p className="mt-4 text-sm text-muted-foreground">Assigned to <strong className="text-foreground">{delivery.assignedToName}</strong></p> : order.fulfilmentMode === "DELIVERY" ? <Link href={`/operator/redeem/${orderId}/assign`} className={`${secondaryActionClassName} mt-4 w-full`}>Assign delivery first</Link> : null}</Card><button type="button" disabled={mutation.isPending || code.status !== "ACTIVE"} onClick={() => mutation.mutate()} className={`${actionClassName} mt-5 w-full`}>{mutation.isPending ? "Completing…" : "Complete handover"} <PackageCheck className="size-4" /></button>{mutation.isError ? <p role="alert" className="mt-3 text-sm text-danger">{mutation.error.message}</p> : null}</div>;
}

export function RedemptionAssignedScreen({ orderId }: { orderId?: string }) {
  const query = useQuery({ enabled:Boolean(orderId), queryKey:["operator-order",OPERATOR_ID,orderId], queryFn:() => operatorOperationsRepository.findOrder(OPERATOR_ID, orderId!) });
  if (!orderId) return <EmptyState title="No assignment selected" description="Open an order before assigning its delivery." action={<Link href="/operator/redeem" className="font-semibold text-primary">Redeem a code</Link>} />;
  if (query.isLoading) return <OperationsLoading />; if (!query.data?.delivery?.assignedToName) return <EmptyState title="Assignment unavailable" description="The delivery assignment was not found." />;
  return <div className="mx-auto max-w-xl text-center"><CheckCircle2 className="mx-auto size-16 text-success" /><PageHeading eyebrow="Assignment saved" title={query.data.delivery.assignedToName} description={`${query.data.order.orderNumber} is assigned with a ${query.data.delivery.etaMinutes}-minute ETA.`} /><Link href={`/operator/redeem/${orderId}`} className={`${actionClassName} mt-7`}>Continue to handover <ArrowRight className="size-4" /></Link></div>;
}

export function RedemptionSuccessScreen({ orderId }: { orderId?: string }) { return <div className="mx-auto max-w-xl text-center"><CheckCircle2 className="mx-auto size-16 text-success" /><p className="mt-5 text-sm font-semibold text-success">Inventory and order updated</p><h1 className="mt-2 text-heading-1 font-semibold">Handover complete</h1><p className="mt-3 text-muted-foreground">The code is redeemed, reusable containers are recorded, and the customer order is complete.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row">{orderId ? <Link href={`/operator/orders/${orderId}`} className={secondaryActionClassName}>View order</Link> : null}<Link href="/operator/redeem" className={actionClassName}>Redeem another</Link></div></div>; }

export function StockScreen() {
  const query = useQuery({ queryKey:["operator-stock",OPERATOR_ID], queryFn:() => operatorOperationsRepository.stock(OPERATOR_ID) });
  return <div><PageHeading eyebrow="Inventory" title="Stock" description="Filled, reserved, empty, and damaged container counts for this business." action={<Link href="/operator/stock/order" className={actionClassName}>Receive stock</Link>} /><div className="mt-5"><Link href="/operator/stock/history" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><History className="size-4" /> Movement history</Link></div>{query.isLoading ? <OperationsLoading /> : <div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data?.map(({inventory,product}) => { const available = inventory.filledQty - inventory.reservedQty; const low = available <= inventory.reorderLevel; return <Card key={inventory.id} className="p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{product?.name}</h2><StatusBadge size="sm" tone={low ? "warning" : "success"}>{low ? "Low" : "Healthy"}</StatusBadge></div><p className="mt-5 text-3xl font-semibold">{available}</p><p className="text-sm text-muted-foreground">available filled units</p><div className="mt-5 grid grid-cols-3 gap-2 border-t border-border pt-4 text-center"><div><strong>{inventory.reservedQty}</strong><span className="block text-xs text-muted-foreground">Reserved</span></div><div><strong>{inventory.emptyQty}</strong><span className="block text-xs text-muted-foreground">Empty</span></div><div><strong>{inventory.damagedQty}</strong><span className="block text-xs text-muted-foreground">Damaged</span></div></div></Card>; })}</div>}</div>;
}

export function StockHistoryScreen() {
  const query = useQuery({ queryKey:["operator-stock-history",OPERATOR_ID], queryFn:() => operatorOperationsRepository.stockHistory(OPERATOR_ID) });
  return <div><PageHeading eyebrow="Inventory audit" title="Stock history" description="Every receipt, reservation, sale, return, and adjustment recorded for your stock." />{query.isLoading ? <OperationsLoading /> : <div className="mt-7 space-y-3">{query.data?.map(({movement,product}) => <Card key={movement.id} className="flex flex-col justify-between gap-3 p-5 sm:flex-row"><div><div className="flex gap-2"><strong>{product?.name ?? "Stock item"}</strong><StatusBadge size="sm" tone={movement.quantity >= 0 ? "success" : "warning"}>{titleCase(movement.type)}</StatusBadge></div><p className="mt-2 text-sm text-muted-foreground">{movement.reason} · {formatDate(movement.createdAt, true)}</p></div><strong className={movement.quantity >= 0 ? "text-success" : "text-warning"}>{movement.quantity >= 0 ? "+" : ""}{movement.quantity}</strong></Card>)}</div>}</div>;
}

export function StockOrderScreen() {
  const router = useRouter(); const query = useQuery({ queryKey:["operator-stock",OPERATOR_ID], queryFn:() => operatorOperationsRepository.stock(OPERATOR_ID) }); const [error,setError] = useState("");
  if (query.isLoading) return <OperationsLoading />;
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const params = new URLSearchParams(); let units=0; query.data?.forEach(({inventory}) => { const q=Number(data.get(inventory.id)); if (Number.isInteger(q) && q>0) { params.set(inventory.id,String(q)); units+=q; } }); const note=String(data.get("note") ?? ""); if (!units) { setError("Add a quantity for at least one product."); return; } if (note.trim().length<4) { setError("Add a delivery reference or note."); return; } params.set("note",note.trim()); router.push(`/operator/stock/order/summary?${params}`); }
  return <div><PageHeading eyebrow="Inventory receipt" title="Receive stock" description="Enter the filled units delivered for each product, then review before posting." /><form onSubmit={submit} className="mt-7 space-y-5"><div className="grid gap-4 md:grid-cols-2">{query.data?.map(({inventory,product}) => <Card key={inventory.id} className="p-5"><FormField id={`qty-${inventory.id}`} label={product?.name ?? "Product"} description={`${inventory.filledQty} currently filled`}>{(props) => <input {...props} name={inventory.id} type="number" min="0" max="500" defaultValue="0" className={formControlClassName} />}</FormField></Card>)}</div><Card className="p-5"><FormField id="stock-note" label="Delivery reference or note" required>{(props) => <input {...props} name="note" placeholder="Supplier delivery 30 Aug" className={formControlClassName} />}</FormField></Card>{error ? <p role="alert" className="text-sm text-danger">{error}</p> : null}<SubmitButton>Review receipt <ArrowRight className="size-4" /></SubmitButton></form></div>;
}

export function StockOrderSummaryScreen({ values }: { values: Record<string,string> }) {
  const router=useRouter(); const client=useQueryClient(); const query=useQuery({queryKey:["operator-stock",OPERATOR_ID],queryFn:() => operatorOperationsRepository.stock(OPERATOR_ID)}); const lines=query.data?.map(({inventory,product}) => ({inventoryId:inventory.id,product,quantity:Number(values[inventory.id] ?? 0)})).filter((line)=>line.quantity>0) ?? [];
  const mutation=useMutation({mutationFn:() => operatorOperationsRepository.receiveStock(OPERATOR_ID,lines,values.note ?? ""),onSuccess:(result)=>{client.invalidateQueries({queryKey:["operator-stock"]});client.invalidateQueries({queryKey:["operator-stock-history"]});router.push(`/operator/stock/order/success?units=${result.units}&reference=${result.reference}`);}});
  if(query.isLoading)return <OperationsLoading/>; if(!lines.length)return <EmptyState title="No stock lines" description="Return to the stock order and add at least one quantity." action={<Link href="/operator/stock/order" className="font-semibold text-primary">Create receipt</Link>}/>;
  return <div className="mx-auto max-w-2xl"><PageHeading eyebrow="Final check" title="Review stock receipt" description="Posting this receipt immediately increases filled inventory and creates audit movements."/><Card className="mt-7 p-6">{lines.map((line)=><div key={line.inventoryId} className="flex justify-between border-b border-border py-3 last:border-0"><span>{line.product?.name}</span><strong>+{line.quantity}</strong></div>)}<p className="mt-4 text-sm text-muted-foreground">Note: {values.note}</p></Card><button type="button" disabled={mutation.isPending} onClick={()=>mutation.mutate()} className={`${actionClassName} mt-5 w-full`}>{mutation.isPending?"Posting…":"Post stock receipt"}</button>{mutation.isError?<p role="alert" className="mt-3 text-sm text-danger">{mutation.error.message}</p>:null}</div>;
}

export function StockOrderSuccessScreen({ units, reference }: { units?: string; reference?: string }) { return <div className="mx-auto max-w-xl text-center"><CheckCircle2 className="mx-auto size-16 text-success"/><p className="mt-5 text-sm font-semibold text-success">{reference ?? "Receipt posted"}</p><h1 className="mt-2 text-heading-1 font-semibold">{units ?? "Stock"} units received</h1><p className="mt-3 text-muted-foreground">Filled inventory and movement history are now up to date.</p><Link href="/operator/stock" className={`${actionClassName} mt-7`}>View stock</Link></div>; }
