"use client";

import { ChevronLeft, ChevronRight, Search } from "lucide-react";
import { useMemo, useState } from "react";
import Link from "next/link";

import { Card, LoadingSkeleton, formControlClassName } from "@/components/ui";

export const adminActionClassName="inline-flex min-h-control items-center justify-center gap-2 rounded-control bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition hover:bg-primary-hover disabled:bg-disabled disabled:text-disabled-foreground";
export const adminSecondaryClassName="inline-flex min-h-control items-center justify-center gap-2 rounded-control border border-border-strong bg-surface px-4 py-2 text-sm font-semibold transition hover:bg-surface-muted disabled:opacity-60";
export function titleCase(value:string){return value.toLowerCase().replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase())}
export function formatAdminDate(value:string,withTime=false){return new Intl.DateTimeFormat("en-GB",withTime?{dateStyle:"medium",timeStyle:"short"}:{dateStyle:"medium"}).format(new Date(value))}
export function adminTone(status:string):"neutral"|"info"|"success"|"warning"|"danger"{if(["ACTIVE","APPROVED","PAID","COMPLETED","REDEEMED"].includes(status))return"success";if(["SUSPENDED","BLOCKED","DELETED","REJECTED","CLOSED","FAILED","CANCELLED","REFUNDED"].includes(status))return"danger";if(["PENDING","PENDING_VERIFICATION","UNASSIGNED","PREPARING"].includes(status))return"warning";if(["CONFIRMED","READY","OUT_FOR_DELIVERY","EN_ROUTE"].includes(status))return"info";return"neutral"}
export function AdminPageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-primary">{eyebrow}</p><h1 className="mt-1 text-heading-1 font-semibold">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{description}</p></div>{action}</header>}
export function AdminLoading({count=4}:{count?:number}){return <div className="mt-7 grid gap-4">{Array.from({length:count},(_,i)=><LoadingSkeleton key={i} className="h-24"/>)}</div>}
export function MetricGrid({items}:{items:Array<{label:string;value:React.ReactNode;hint?:string}>}){return <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map(item=><Card key={item.label} className="p-5"><p className="text-sm text-muted-foreground">{item.label}</p><p className="mt-2 text-3xl font-semibold">{item.value}</p>{item.hint?<p className="mt-2 text-xs text-muted-foreground">{item.hint}</p>:null}</Card>)}</div>}

export function useAdminCollection<Row>(rows:readonly Row[],options:{searchText:(row:Row)=>string;filterValue?:(row:Row)=>string;pageSize?:number}){
  const [search,setSearch]=useState("");const [filter,setFilter]=useState("ALL");const [page,setPage]=useState(1);const pageSize=options.pageSize??6;
  const filtered=useMemo(()=>rows.filter(row=>options.searchText(row).toLowerCase().includes(search.trim().toLowerCase())&&(filter==="ALL"||options.filterValue?.(row)===filter)),[rows,search,filter,options]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const safePage=Math.min(page,pages);const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  return {search,filter,page:safePage,pages,total:filtered.length,visible,setSearch:(value:string)=>{setSearch(value);setPage(1)},setFilter:(value:string)=>{setFilter(value);setPage(1)},setPage};
}
export function DirectoryControls({search,onSearch,filter,onFilter,filters,total,label}:{search:string;onSearch:(v:string)=>void;filter:string;onFilter:(v:string)=>void;filters:Array<{value:string;label:string}>;total:number;label:string}){return <div className="mt-7 flex flex-col gap-3 rounded-card border border-border bg-surface p-4 shadow-card sm:flex-row sm:items-center"><label className="relative flex-1"><span className="sr-only">Search {label}</span><Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={e=>onSearch(e.target.value)} placeholder={`Search ${label}`} className={`${formControlClassName} pl-10`}/></label><label><span className="sr-only">Filter {label}</span><select value={filter} onChange={e=>onFilter(e.target.value)} className={formControlClassName}><option value="ALL">All statuses</option>{filters.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><p className="text-sm text-muted-foreground sm:min-w-24 sm:text-right">{total} result{total===1?"":"s"}</p></div>}
export function Pagination({page,pages,onPage}:{page:number;pages:number;onPage:(p:number)=>void}){return <nav aria-label="Pagination" className="mt-5 flex items-center justify-between"><button type="button" onClick={()=>onPage(page-1)} disabled={page<=1} className={adminSecondaryClassName}><ChevronLeft className="size-4"/>Previous</button><p className="text-sm text-muted-foreground">Page {page} of {pages}</p><button type="button" onClick={()=>onPage(page+1)} disabled={page>=pages} className={adminSecondaryClassName}>Next<ChevronRight className="size-4"/></button></nav>}
export function EntityNav({items}:{items:Array<{href:string;label:string}>}){return <nav aria-label="Record sections" className="mt-5 flex gap-2 overflow-x-auto pb-1">{items.map(item=><Link key={item.href} href={item.href} className="shrink-0 rounded-pill border border-border-strong bg-surface px-4 py-2 text-sm font-semibold hover:border-primary hover:text-primary">{item.label}</Link>)}</nav>}
