"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, Building2, MapPin, Star, Store, Truck } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Card, ConfirmDialog, DataTable, EmptyState, StatusBadge } from "@/components/ui";
import { adminAccountsRepository } from "@/data";
import type { BusinessStatus, Delivery, LedgerEntry, Order, Review, VerificationRequest } from "@/domain/types";
import { AdminLoading, AdminPageHeading, DirectoryControls, EntityNav, MetricGrid, Pagination, adminSecondaryClassName, adminTone, formatAdminDate, titleCase, useAdminCollection } from "@/features/admin-accounts/admin-ui";
import { formatMoney } from "@/lib/money";

type BusinessRow=Awaited<ReturnType<typeof adminAccountsRepository.businesses>>[number];
type BusinessDetail=NonNullable<Awaited<ReturnType<typeof adminAccountsRepository.business>>>;
type StockRow=BusinessDetail["stock"][number];
const businessNav=(id:string)=>[{href:`/admin/businesses/${id}`,label:"Overview"},{href:`/admin/businesses/${id}/profile`,label:"Profile"},{href:`/admin/businesses/${id}/stock`,label:"Stock"},{href:`/admin/businesses/${id}/deliveries`,label:"Deliveries"},{href:`/admin/businesses/${id}/orders`,label:"Orders"},{href:`/admin/businesses/${id}/earnings`,label:"Earnings"},{href:`/admin/businesses/${id}/compliance`,label:"Compliance"},{href:`/admin/businesses/${id}/ratings`,label:"Ratings"}];
function useBusiness(id:string){return useQuery({queryKey:["admin-business",id],queryFn:()=>adminAccountsRepository.business(id)})}
function BusinessHeader({detail,section,description}:{detail:BusinessDetail;section:string;description:string}){return <><AdminPageHeading eyebrow={detail.business.name} title={section} description={description} action={<StatusBadge tone={adminTone(detail.business.status)}>{titleCase(detail.business.status)}</StatusBadge>}/><EntityNav items={businessNav(detail.business.id)}/></>}

export function BusinessesScreen(){const query=useQuery({queryKey:["admin-businesses"],queryFn:()=>adminAccountsRepository.businesses()});const rows=query.data??[];const c=useAdminCollection(rows,{searchText:r=>`${r.business.name} ${r.business.email} ${r.operator?.legalName??""}`,filterValue:r=>r.business.status});const columns=[{id:"business",header:"Business",cell:(r:BusinessRow)=><div><Link href={`/admin/businesses/${r.business.id}`} className="font-semibold text-primary">{r.business.name}</Link><p className="mt-1 text-xs text-muted-foreground">{r.user?`${r.user.firstName} ${r.user.lastName}`:"No owner"}</p></div>},{id:"status",header:"Status",cell:(r:BusinessRow)=><StatusBadge size="sm" tone={adminTone(r.business.status)}>{titleCase(r.business.status)}</StatusBadge>},{id:"orders",header:"Orders",align:"right" as const,cell:(r:BusinessRow)=>r.orderCount},{id:"stock",header:"Available stock",align:"right" as const,cell:(r:BusinessRow)=>r.availableStock},{id:"rating",header:"Rating",align:"right" as const,cell:(r:BusinessRow)=>r.business.rating.toFixed(1)}];return <div><AdminPageHeading eyebrow="Account management" title="Businesses" description="Search every refill partner and inspect operational health, ownership, and compliance."/><DirectoryControls search={c.search} onSearch={c.setSearch} filter={c.filter} onFilter={c.setFilter} filters={[{value:"ACTIVE",label:"Active"},{value:"PENDING_VERIFICATION",label:"Pending verification"},{value:"SUSPENDED",label:"Suspended"},{value:"CLOSED",label:"Closed"}]} total={c.total} label="businesses"/>{query.isLoading?<AdminLoading/>:<DataTable className="mt-4" rows={c.visible} columns={columns} getRowKey={r=>r.business.id} caption="Platform businesses"/>}<Pagination page={c.page} pages={c.pages} onPage={c.setPage}/></div>}

export function BusinessOverviewAdminScreen({businessId}:{businessId:string}){const client=useQueryClient();const query=useBusiness(businessId);const [status,setStatus]=useState<BusinessStatus|null>(null);const mutation=useMutation({mutationFn:(value:BusinessStatus)=>adminAccountsRepository.setBusinessStatus(businessId,value),onSuccess:()=>{setStatus(null);client.invalidateQueries({queryKey:["admin-business",businessId]});client.invalidateQueries({queryKey:["admin-businesses"]});client.invalidateQueries({queryKey:["admin-dashboard"]})}});if(query.isLoading)return <AdminLoading/>;if(!query.data)return <EmptyState icon={Store} title="Business not found" description="This business record is unavailable."/>;const d=query.data;const available=d.stock.reduce((sum,row)=>sum+Math.max(0,row.inventory.filledQty-row.inventory.reservedQty),0);const paid=d.orders.filter(o=>o.paymentStatus==="PAID").reduce((sum,o)=>sum+o.total,0);const actionVerb=status==="ACTIVE"?"Activate":status==="SUSPENDED"?"Suspend":status==="CLOSED"?"Close":"Update";return <div><BusinessHeader detail={d} section="Business overview" description={`${d.operator?.legalName??"Unassigned operator"} · created ${formatAdminDate(d.business.createdAt)}`}/><MetricGrid items={[{label:"Orders",value:d.orders.length},{label:"Paid order value",value:formatMoney(paid)},{label:"Available stock",value:available},{label:"Customer rating",value:d.business.rating.toFixed(1),hint:`${d.business.reviewCount} platform reviews`}]}/><Card className="mt-6 p-6"><h2 className="font-semibold">Business status</h2><p className="mt-2 text-sm text-muted-foreground">Suspending or closing a business also removes it from customer ordering by setting it closed.</p><div className="mt-5 flex flex-wrap gap-3"><button disabled={d.business.status==="ACTIVE"} onClick={()=>setStatus("ACTIVE")} className={adminSecondaryClassName}>Activate</button><button disabled={d.business.status==="SUSPENDED"} onClick={()=>setStatus("SUSPENDED")} className={adminSecondaryClassName}>Suspend</button><button disabled={d.business.status==="CLOSED"} onClick={()=>setStatus("CLOSED")} className="min-h-control rounded-control bg-danger px-4 text-sm font-semibold text-white disabled:bg-disabled">Close business</button></div></Card><ConfirmDialog open={Boolean(status)} onOpenChange={open=>!open&&setStatus(null)} title={`${actionVerb} this business?`} description="This changes customer availability and the shared business status record." confirmLabel="Confirm status" tone={status==="CLOSED"?"danger":"default"} pending={mutation.isPending} onConfirm={()=>status&&mutation.mutate(status)}/></div>}

export function BusinessProfileAdminScreen({businessId}:{businessId:string}){const q=useBusiness(businessId);if(q.isLoading)return <AdminLoading/>;if(!q.data)return <EmptyState title="Business not found" description="Profile data is unavailable."/>;const d=q.data;return <div><BusinessHeader detail={d} section="Business profile" description="Public listing information, ownership, location, and service configuration."/><div className="mt-7 grid gap-5 lg:grid-cols-2"><Card className="p-6"><Building2 className="size-6 text-primary"/><h2 className="mt-4 font-semibold">Public listing</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{d.business.description}</p><p className="mt-4 text-sm">{d.business.email}<br/>{d.business.phone}</p></Card><Card className="p-6"><MapPin className="size-6 text-primary"/><h2 className="mt-4 font-semibold">Location and fulfilment</h2><p className="mt-3 text-sm">{d.address?[d.address.line1,d.address.city,d.address.state].join(", "):"Address unavailable"}</p><p className="mt-3 text-sm text-muted-foreground">{d.business.fulfilmentModes.map(titleCase).join(" and ")} · {d.business.deliveryRadiusKm} km radius · minimum {formatMoney(d.business.minimumOrder)}</p></Card></div><Card className="mt-5 p-6"><h2 className="font-semibold">Ownership</h2><p className="mt-3 text-sm">{d.user?`${d.user.firstName} ${d.user.lastName}`:"Unknown owner"} · {d.operator?.legalName}</p>{d.operator?<Link href={`/admin/operators/${d.operator.id}`} className="mt-4 inline-flex text-sm font-semibold text-primary">Open operator record</Link>:null}</Card></div>}

export function BusinessStockAdminScreen({businessId}:{businessId:string}){const q=useBusiness(businessId);if(q.isLoading)return <AdminLoading/>;if(!q.data)return <EmptyState title="Business not found" description="Stock data is unavailable."/>;const columns=[{id:"product",header:"Product",cell:(r:StockRow)=><strong>{r.product?.name??r.inventory.productId}</strong>},{id:"filled",header:"Filled",align:"right" as const,cell:(r:StockRow)=>r.inventory.filledQty},{id:"reserved",header:"Reserved",align:"right" as const,cell:(r:StockRow)=>r.inventory.reservedQty},{id:"empty",header:"Empty",align:"right" as const,cell:(r:StockRow)=>r.inventory.emptyQty},{id:"health",header:"Health",cell:(r:StockRow)=>{const low=r.inventory.filledQty-r.inventory.reservedQty<=r.inventory.reorderLevel;return <StatusBadge size="sm" tone={low?"warning":"success"}>{low?"Low":"Healthy"}</StatusBadge>}}];return <div><BusinessHeader detail={q.data} section="Stock" description="Filled, reserved, empty, damaged, and reorder-level inventory."/><DataTable className="mt-7" rows={q.data.stock} columns={columns} getRowKey={r=>r.inventory.id} caption="Business inventory"/></div>}

export function BusinessDeliveriesAdminScreen({businessId}:{businessId:string}){const q=useBusiness(businessId);if(q.isLoading)return <AdminLoading/>;if(!q.data)return <EmptyState icon={Truck} title="Business not found" description="Delivery data is unavailable."/>;const columns=[{id:"delivery",header:"Delivery",cell:(r:Delivery)=><span className="font-mono font-semibold">{r.id}</span>},{id:"order",header:"Order",cell:(r:Delivery)=>r.orderId},{id:"assignee",header:"Assignee",cell:(r:Delivery)=>r.assignedToName??"Unassigned"},{id:"status",header:"Status",cell:(r:Delivery)=><StatusBadge size="sm" tone={adminTone(r.status)}>{titleCase(r.status)}</StatusBadge>},{id:"eta",header:"ETA",align:"right" as const,cell:(r:Delivery)=>r.etaMinutes?`${r.etaMinutes} min`:"—"}];return <div><BusinessHeader detail={q.data} section="Deliveries" description="Assignments and fulfilment progress for delivery orders."/><DataTable className="mt-7" rows={q.data.deliveries} columns={columns} getRowKey={r=>r.id} caption="Business deliveries" emptyState="No deliveries for this business."/></div>}

export function BusinessOrdersAdminScreen({businessId}:{businessId:string}){const q=useBusiness(businessId);if(q.isLoading)return <AdminLoading/>;if(!q.data)return <EmptyState title="Business not found" description="Order data is unavailable."/>;const columns=[{id:"order",header:"Order",cell:(r:Order)=><span className="font-mono font-semibold">{r.orderNumber}</span>},{id:"customer",header:"Customer",cell:(r:Order)=><Link href={`/admin/customers/${r.customerId}`} className="text-primary">{r.customerId}</Link>},{id:"status",header:"Status",cell:(r:Order)=><StatusBadge size="sm" tone={adminTone(r.status)}>{titleCase(r.status)}</StatusBadge>},{id:"date",header:"Created",cell:(r:Order)=>formatAdminDate(r.createdAt)},{id:"total",header:"Total",align:"right" as const,cell:(r:Order)=>formatMoney(r.total)}];return <div><BusinessHeader detail={q.data} section="Orders" description="All customer orders attributed to this business."/><DataTable className="mt-7" rows={q.data.orders} columns={columns} getRowKey={r=>r.id} caption="Business orders"/></div>}

export function BusinessEarningsAdminScreen({businessId}:{businessId:string}){const q=useBusiness(businessId);if(q.isLoading)return <AdminLoading/>;if(!q.data)return <EmptyState title="Business not found" description="Earnings data is unavailable."/>;const total=q.data.earnings.reduce((s,e)=>s+e.amount,0);const columns=[{id:"entry",header:"Entry",cell:(r:LedgerEntry)=><div><strong>{r.description}</strong><p className="mt-1 text-xs text-muted-foreground">{r.referenceId}</p></div>},{id:"date",header:"Created",cell:(r:LedgerEntry)=>formatAdminDate(r.createdAt,true)},{id:"amount",header:"Amount",align:"right" as const,cell:(r:LedgerEntry)=><strong className="text-success">+{formatMoney(r.amount)}</strong>}];return <div><BusinessHeader detail={q.data} section="Earnings" description="Order-earning ledger entries from the linked operator wallet."/><MetricGrid items={[{label:"Recorded earnings",value:formatMoney(total)},{label:"Ledger entries",value:q.data.earnings.length},{label:"Operator wallet",value:formatMoney(q.data.wallet?.cachedBalance??0)},{label:"Currency",value:q.data.wallet?.currency??"GBP"}]}/><DataTable className="mt-7" rows={q.data.earnings} columns={columns} getRowKey={r=>r.id} caption="Business earnings" emptyState="No earnings recorded."/></div>}

export function BusinessComplianceAdminScreen({businessId}:{businessId:string}){const q=useBusiness(businessId);if(q.isLoading)return <AdminLoading/>;if(!q.data)return <EmptyState title="Business not found" description="Compliance data is unavailable."/>;return <div><BusinessHeader detail={q.data} section="Compliance" description="Verification submissions, review status, and administrative notes."/><div className="mt-7 space-y-4">{q.data.verification.length?q.data.verification.map((r:VerificationRequest)=><Card key={r.id} className="p-6"><div className="flex justify-between gap-3"><div><strong>{r.id}</strong><p className="mt-1 text-sm text-muted-foreground">Submitted {formatAdminDate(r.submittedAt,true)}</p></div><StatusBadge tone={adminTone(r.status)}>{titleCase(r.status)}</StatusBadge></div><p className="mt-5 rounded-control bg-surface-muted p-4 text-sm">{r.notes??"No reviewer notes."}</p>{r.reviewedAt?<p className="mt-3 text-xs text-muted-foreground">Reviewed {formatAdminDate(r.reviewedAt,true)} by {r.reviewerId}</p>:null}</Card>):<EmptyState icon={BadgeCheck} title="No compliance request" description="This business has not submitted a verification request."/>}</div></div>}

export function BusinessRatingsAdminScreen({businessId}:{businessId:string}){const q=useBusiness(businessId);if(q.isLoading)return <AdminLoading/>;if(!q.data)return <EmptyState title="Business not found" description="Rating data is unavailable."/>;const columns=[{id:"rating",header:"Rating",cell:(r:Review)=><span className="inline-flex items-center gap-1 font-semibold text-warning"><Star className="size-4 fill-warning"/>{r.rating}/5</span>},{id:"customer",header:"Customer",cell:(r:Review)=><Link href={`/admin/customers/${r.customerId}`} className="text-primary">{r.customerId}</Link>},{id:"body",header:"Review",cell:(r:Review)=><p className="max-w-xl">{r.body}</p>},{id:"date",header:"Created",cell:(r:Review)=>formatAdminDate(r.createdAt)}];return <div><BusinessHeader detail={q.data} section="Ratings" description={`Customer feedback for this business. Displayed rating: ${q.data.business.rating.toFixed(1)}.`}/><DataTable className="mt-7" rows={q.data.reviews} columns={columns} getRowKey={r=>r.id} caption="Business ratings" emptyState="No seeded review records."/></div>}
