"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Ban, MapPin, ShieldCheck, Star, UserRound } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Card, ConfirmDialog, DataTable, EmptyState, StatusBadge } from "@/components/ui";
import { adminAccountsRepository } from "@/data";
import type { Order, Review } from "@/domain/types";
import { AdminLoading, AdminPageHeading, DirectoryControls, EntityNav, MetricGrid, Pagination, adminSecondaryClassName, adminTone, formatAdminDate, titleCase, useAdminCollection } from "@/features/admin-accounts/admin-ui";
import { formatMoney } from "@/lib/money";

type CustomerRow=Awaited<ReturnType<typeof adminAccountsRepository.customers>>[number];
const customerNav=(id:string)=>[{href:`/admin/customers/${id}`,label:"Overview"},{href:`/admin/customers/${id}/profile`,label:"Profile"},{href:`/admin/customers/${id}/orders`,label:"Orders"},{href:`/admin/customers/${id}/ratings`,label:"Ratings"}];

export function CustomersScreen(){const query=useQuery({queryKey:["admin-customers"],queryFn:()=>adminAccountsRepository.customers()});const rows=query.data??[];const collection=useAdminCollection(rows,{searchText:row=>`${row.user.firstName} ${row.user.lastName} ${row.user.email} ${row.user.phone}`,filterValue:row=>row.user.status});const columns=[{id:"customer",header:"Customer",cell:(row:CustomerRow)=><div><Link href={`/admin/customers/${row.user.id}`} className="font-semibold text-primary">{row.user.firstName} {row.user.lastName}</Link><p className="mt-1 text-xs text-muted-foreground">{row.user.email}</p></div>},{id:"status",header:"Status",cell:(row:CustomerRow)=><StatusBadge size="sm" tone={adminTone(row.user.status)}>{titleCase(row.user.status)}</StatusBadge>},{id:"orders",header:"Orders",align:"right" as const,cell:(row:CustomerRow)=>row.orderCount},{id:"spend",header:"Paid value",align:"right" as const,cell:(row:CustomerRow)=>formatMoney(row.spend)}];return <div><AdminPageHeading eyebrow="Account management" title="Customers" description="Search customer accounts, inspect activity, and apply reversible access controls."/><DirectoryControls search={collection.search} onSearch={collection.setSearch} filter={collection.filter} onFilter={collection.setFilter} filters={[{value:"ACTIVE",label:"Active"},{value:"SUSPENDED",label:"Suspended"},{value:"BLOCKED",label:"Blocked"},{value:"PENDING",label:"Pending"}]} total={collection.total} label="customers"/>{query.isLoading?<AdminLoading/>:<DataTable className="mt-4" rows={collection.visible} columns={columns} getRowKey={row=>row.user.id} caption="Customer accounts"/>}<Pagination page={collection.page} pages={collection.pages} onPage={collection.setPage}/></div>}

function useCustomer(id:string){return useQuery({queryKey:["admin-customer",id],queryFn:()=>adminAccountsRepository.customer(id)})}
export function CustomerOverviewScreen({customerId}:{customerId:string}){const client=useQueryClient();const query=useCustomer(customerId);const [nextStatus,setNextStatus]=useState<"ACTIVE"|"SUSPENDED"|"BLOCKED"|null>(null);const mutation=useMutation({mutationFn:(status:"ACTIVE"|"SUSPENDED"|"BLOCKED")=>adminAccountsRepository.setCustomerStatus(customerId,status),onSuccess:()=>{setNextStatus(null);client.invalidateQueries({queryKey:["admin-customer",customerId]});client.invalidateQueries({queryKey:["admin-customers"]})}});if(query.isLoading)return <AdminLoading/>;if(!query.data)return <EmptyState icon={UserRound} title="Customer not found" description="This customer record is unavailable."/>;const {user,orders,reviews,payments,wallet}=query.data;const actionVerb=nextStatus==="ACTIVE"?"Activate":nextStatus==="SUSPENDED"?"Suspend":nextStatus==="BLOCKED"?"Block":"Update";return <div><AdminPageHeading eyebrow="Customer record" title={`${user.firstName} ${user.lastName}`} description={`${user.email} · joined ${formatAdminDate(user.createdAt)}`} action={<StatusBadge tone={adminTone(user.status)}>{titleCase(user.status)}</StatusBadge>}/><EntityNav items={customerNav(customerId)}/><MetricGrid items={[{label:"Orders",value:orders.length},{label:"Paid transactions",value:payments.filter(p=>p.status==="PAID").length},{label:"Reviews",value:reviews.length},{label:"Wallet balance",value:formatMoney(wallet?.cachedBalance??0)}]}/><Card className="mt-6 p-6"><h2 className="font-semibold">Account actions</h2><p className="mt-2 text-sm text-muted-foreground">Access changes take effect across the shared demo account record.</p><div className="mt-5 flex flex-wrap gap-3">{user.status!=="ACTIVE"?<button onClick={()=>setNextStatus("ACTIVE")} className={adminSecondaryClassName}>Activate account</button>:null}{user.status!=="SUSPENDED"?<button onClick={()=>setNextStatus("SUSPENDED")} className={adminSecondaryClassName}>Suspend account</button>:null}{user.status!=="BLOCKED"?<button onClick={()=>setNextStatus("BLOCKED")} className="inline-flex min-h-control items-center gap-2 rounded-control bg-danger px-4 text-sm font-semibold text-white"><Ban className="size-4"/>Block account</button>:null}</div></Card><ConfirmDialog open={Boolean(nextStatus)} onOpenChange={open=>!open&&setNextStatus(null)} title={`${actionVerb} this customer?`} description="This updates the sign-in status for the customer account." confirmLabel="Confirm status change" tone={nextStatus==="BLOCKED"?"danger":"default"} pending={mutation.isPending} onConfirm={()=>nextStatus&&mutation.mutate(nextStatus)}/></div>}

export function CustomerProfileAdminScreen({customerId}:{customerId:string}){const query=useCustomer(customerId);if(query.isLoading)return <AdminLoading/>;if(!query.data)return <EmptyState title="Customer not found" description="Profile data is unavailable."/>;const {user,addresses,wallet,ledger}=query.data;return <div><AdminPageHeading eyebrow="Customer details" title={`${user.firstName} ${user.lastName}`} description="Identity, contact, saved locations, and wallet audit."/><EntityNav items={customerNav(customerId)}/><div className="mt-7 grid gap-5 lg:grid-cols-2"><Card className="p-6"><ShieldCheck className="size-6 text-primary"/><h2 className="mt-4 font-semibold">Contact and verification</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-muted-foreground">Email</dt><dd>{user.email} · {user.isEmailVerified?"verified":"unverified"}</dd></div><div><dt className="text-muted-foreground">Phone</dt><dd>{user.phone} · {user.isPhoneVerified?"verified":"unverified"}</dd></div></dl></Card><Card className="p-6"><MapPin className="size-6 text-primary"/><h2 className="mt-4 font-semibold">Saved addresses</h2>{addresses.map(a=><p key={a.id} className="mt-3 text-sm"><strong>{titleCase(a.label)}</strong><br/><span className="text-muted-foreground">{[a.line1,a.city,a.state].join(", ")}</span></p>)}</Card></div><Card className="mt-5 p-6"><h2 className="font-semibold">Wallet ledger</h2><p className="mt-2 text-2xl font-semibold">{formatMoney(wallet?.cachedBalance??0)}</p><div className="mt-4 space-y-2">{ledger.map(entry=><div key={entry.id} className="flex justify-between border-t border-border pt-3 text-sm"><span>{entry.description}</span><strong>{entry.direction==="CREDIT"?"+":"−"}{formatMoney(entry.amount)}</strong></div>)}</div></Card></div>}

export function CustomerOrdersAdminScreen({customerId}:{customerId:string}){const query=useCustomer(customerId);if(query.isLoading)return <AdminLoading/>;if(!query.data)return <EmptyState title="Customer not found" description="Order data is unavailable."/>;const columns=[{id:"order",header:"Order",cell:(row:Order)=><span className="font-mono font-semibold">{row.orderNumber}</span>},{id:"status",header:"Status",cell:(row:Order)=><StatusBadge size="sm" tone={adminTone(row.status)}>{titleCase(row.status)}</StatusBadge>},{id:"date",header:"Created",cell:(row:Order)=>formatAdminDate(row.createdAt)},{id:"total",header:"Total",align:"right" as const,cell:(row:Order)=>formatMoney(row.total)}];return <div><AdminPageHeading eyebrow="Customer orders" title={`${query.data.user.firstName} ${query.data.user.lastName}`} description="Every order associated with this customer account."/><EntityNav items={customerNav(customerId)}/><DataTable className="mt-7" rows={query.data.orders} columns={columns} getRowKey={row=>row.id} caption="Customer orders"/></div>}

export function CustomerRatingsAdminScreen({customerId}:{customerId:string}){const query=useCustomer(customerId);if(query.isLoading)return <AdminLoading/>;if(!query.data)return <EmptyState title="Customer not found" description="Rating data is unavailable."/>;const columns=[{id:"rating",header:"Rating",cell:(row:Review)=><span className="inline-flex items-center gap-1 font-semibold text-warning"><Star className="size-4 fill-warning"/>{row.rating}/5</span>},{id:"review",header:"Review",cell:(row:Review)=><p className="max-w-xl">{row.body}</p>},{id:"date",header:"Created",cell:(row:Review)=>formatAdminDate(row.createdAt)}];return <div><AdminPageHeading eyebrow="Customer feedback" title={`${query.data.user.firstName} ${query.data.user.lastName}`} description="Ratings this customer submitted after completed orders."/><EntityNav items={customerNav(customerId)}/><DataTable className="mt-7" rows={query.data.reviews} columns={columns} getRowKey={row=>row.id} caption="Customer ratings" emptyState="This customer has not submitted a review."/></div>}
