"use client";

import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BadgeCheck, HandCoins, Package, Users } from "lucide-react";
import Link from "next/link";

import { Card, DataTable, StatusBadge } from "@/components/ui";
import { adminAccountsRepository } from "@/data";
import type { Order } from "@/domain/types";
import { AdminLoading, AdminPageHeading, MetricGrid, adminTone, formatAdminDate, titleCase } from "@/features/admin-accounts/admin-ui";
import { formatMoney } from "@/lib/money";

export function AdminDashboardScreen(){const query=useQuery({queryKey:["admin-dashboard"],queryFn:()=>adminAccountsRepository.dashboard()});if(query.isLoading)return <AdminLoading/>;if(!query.data)return null;const d=query.data;const columns=[{id:"order",header:"Order",cell:(row:Order)=><Link href={`/admin/businesses/${row.businessId}/orders`} className="font-mono font-semibold text-primary">{row.orderNumber}</Link>},{id:"status",header:"Status",cell:(row:Order)=><StatusBadge size="sm" tone={adminTone(row.status)}>{titleCase(row.status)}</StatusBadge>},{id:"date",header:"Created",cell:(row:Order)=>formatAdminDate(row.createdAt)},{id:"total",header:"Total",align:"right" as const,cell:(row:Order)=><strong>{formatMoney(row.total)}</strong>}];return <div><AdminPageHeading eyebrow="Platform control" title="Admin dashboard" description="A live overview of accounts, fulfilment, verification, payouts, and stock health."/><MetricGrid items={[{label:"Customers",value:d.customers,hint:`${d.operators} operators`},{label:"Active businesses",value:d.activeBusinesses,hint:`${d.businesses} total`},{label:"Active orders",value:d.activeOrders,hint:`${formatMoney(d.orderValue)} paid value`},{label:"Items needing attention",value:d.pendingVerification+d.pendingWithdrawals+d.lowStock,hint:"Verification, payouts, and stock"}]}/><div className="mt-6 grid gap-4 md:grid-cols-3"><Link href="/admin/customers"><Card className="p-5 transition hover:border-primary"><Users className="size-5 text-primary"/><h2 className="mt-3 font-semibold">Account directory</h2><p className="mt-1 text-sm text-muted-foreground">Customers, operators, and businesses</p></Card></Link><Link href="/admin/businesses"><Card className="p-5 transition hover:border-primary"><Package className="size-5 text-primary"/><h2 className="mt-3 font-semibold">{d.lowStock} low-stock lines</h2><p className="mt-1 text-sm text-muted-foreground">Review business inventory</p></Card></Link><Link href="/admin/operators"><Card className="p-5 transition hover:border-primary"><BadgeCheck className="size-5 text-primary"/><h2 className="mt-3 font-semibold">{d.pendingVerification} verification request</h2><p className="mt-1 text-sm text-muted-foreground">Review operator compliance</p></Card></Link></div><div className="mt-8 flex justify-between"><h2 className="text-heading-2 font-semibold">Recent orders</h2><Link href="/admin/businesses" className="inline-flex items-center gap-1 text-sm font-semibold text-primary">Explore businesses<ArrowRight className="size-4"/></Link></div><DataTable className="mt-4" rows={d.recentOrders} columns={columns} getRowKey={row=>row.id} caption="Recent platform orders"/><p className="mt-5 inline-flex items-center gap-2 text-sm text-muted-foreground"><HandCoins className="size-4"/>{d.pendingWithdrawals} withdrawal request awaiting review</p></div>}
