"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, Building2, Landmark, UserCog } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Card, ConfirmDialog, DataTable, EmptyState, StatusBadge } from "@/components/ui";
import { adminAccountsRepository } from "@/data";
import type { Business, VerificationRequest, Withdrawal } from "@/domain/types";
import { AdminLoading, AdminPageHeading, DirectoryControls, EntityNav, MetricGrid, Pagination, adminSecondaryClassName, adminTone, formatAdminDate, titleCase, useAdminCollection } from "@/features/admin-accounts/admin-ui";
import { formatMoney } from "@/lib/money";

type OperatorRow=Awaited<ReturnType<typeof adminAccountsRepository.operators>>[number];
const operatorNav=(id:string)=>[{href:`/admin/operators/${id}`,label:"Overview"},{href:`/admin/operators/${id}/profile`,label:"Profile"}];
export function OperatorsScreen(){const query=useQuery({queryKey:["admin-operators"],queryFn:()=>adminAccountsRepository.operators()});const rows=query.data??[];const c=useAdminCollection(rows,{searchText:r=>`${r.operator.legalName} ${r.operator.tradingName} ${r.user.email}`,filterValue:r=>r.operator.status});const columns=[{id:"operator",header:"Operator",cell:(r:OperatorRow)=><div><Link href={`/admin/operators/${r.operator.id}`} className="font-semibold text-primary">{r.operator.tradingName}</Link><p className="mt-1 text-xs text-muted-foreground">{r.operator.legalName}</p></div>},{id:"status",header:"Verification",cell:(r:OperatorRow)=><StatusBadge size="sm" tone={adminTone(r.operator.status)}>{titleCase(r.operator.status)}</StatusBadge>},{id:"businesses",header:"Businesses",align:"right" as const,cell:(r:OperatorRow)=>r.businessCount},{id:"balance",header:"Balance",align:"right" as const,cell:(r:OperatorRow)=>formatMoney(r.balance)}];return <div><AdminPageHeading eyebrow="Account management" title="Operators" description="Review operator ownership, verification, business activity, and settlement balances."/><DirectoryControls search={c.search} onSearch={c.setSearch} filter={c.filter} onFilter={c.setFilter} filters={[{value:"APPROVED",label:"Approved"},{value:"PENDING",label:"Pending"},{value:"REJECTED",label:"Rejected"}]} total={c.total} label="operators"/>{query.isLoading?<AdminLoading/>:<DataTable className="mt-4" rows={c.visible} columns={columns} getRowKey={r=>r.operator.id} caption="Operator accounts"/>}<Pagination page={c.page} pages={c.pages} onPage={c.setPage}/></div>}
function useOperator(id:string){return useQuery({queryKey:["admin-operator",id],queryFn:()=>adminAccountsRepository.operator(id)})}
export function OperatorOverviewAdminScreen({operatorId}:{operatorId:string}){const client=useQueryClient();const query=useOperator(operatorId);const [status,setStatus]=useState<"APPROVED"|"PENDING"|"REJECTED"|null>(null);const mutation=useMutation({mutationFn:(value:"APPROVED"|"PENDING"|"REJECTED")=>adminAccountsRepository.setOperatorStatus(operatorId,value),onSuccess:()=>{setStatus(null);client.invalidateQueries({queryKey:["admin-operator",operatorId]});client.invalidateQueries({queryKey:["admin-operators"]});client.invalidateQueries({queryKey:["admin-businesses"]})}});if(query.isLoading)return <AdminLoading/>;if(!query.data)return <EmptyState icon={UserCog} title="Operator not found" description="This operator record is unavailable."/>;const d=query.data;const actionVerb=status==="APPROVED"?"Approve":status==="PENDING"?"Return to pending":status==="REJECTED"?"Reject":"Update";return <div><AdminPageHeading eyebrow="Operator record" title={d.operator.tradingName} description={`${d.operator.legalName} · ${d.user.email}`} action={<StatusBadge tone={adminTone(d.operator.status)}>{titleCase(d.operator.status)}</StatusBadge>}/><EntityNav items={operatorNav(operatorId)}/><MetricGrid items={[{label:"Businesses",value:d.businesses.length},{label:"Orders",value:d.orders.length},{label:"Wallet",value:formatMoney(d.wallet?.cachedBalance??0)},{label:"Withdrawals",value:d.withdrawals.length}]}/><Card className="mt-6 p-6"><h2 className="font-semibold">Verification action</h2><div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>setStatus("APPROVED")} disabled={d.operator.status==="APPROVED"} className={adminSecondaryClassName}><BadgeCheck className="size-4"/>Approve</button><button onClick={()=>setStatus("PENDING")} disabled={d.operator.status==="PENDING"} className={adminSecondaryClassName}>Return to pending</button><button onClick={()=>setStatus("REJECTED")} disabled={d.operator.status==="REJECTED"} className="min-h-control rounded-control bg-danger px-4 text-sm font-semibold text-white disabled:bg-disabled">Reject operator</button></div></Card><ConfirmDialog open={Boolean(status)} onOpenChange={open=>!open&&setStatus(null)} title={`${actionVerb} this operator?`} description="Rejecting also suspends the linked sign-in account. Approval reactivates it." confirmLabel="Confirm verification" tone={status==="REJECTED"?"danger":"default"} pending={mutation.isPending} onConfirm={()=>status&&mutation.mutate(status)}/></div>}
export function OperatorProfileAdminScreen({operatorId}:{operatorId:string}){const query=useOperator(operatorId);if(query.isLoading)return <AdminLoading/>;if(!query.data)return <EmptyState title="Operator not found" description="Profile data is unavailable."/>;const d=query.data;const businessColumns=[{id:"business",header:"Business",cell:(r:Business)=><Link href={`/admin/businesses/${r.id}`} className="font-semibold text-primary">{r.name}</Link>},{id:"status",header:"Status",cell:(r:Business)=><StatusBadge size="sm" tone={adminTone(r.status)}>{titleCase(r.status)}</StatusBadge>},{id:"rating",header:"Rating",align:"right" as const,cell:(r:Business)=>`${r.rating.toFixed(1)} (${r.reviewCount})`}];const withdrawalColumns=[{id:"amount",header:"Amount",cell:(r:Withdrawal)=>formatMoney(r.amount)},{id:"status",header:"Status",cell:(r:Withdrawal)=><StatusBadge size="sm" tone={adminTone(r.status)}>{titleCase(r.status)}</StatusBadge>},{id:"date",header:"Requested",cell:(r:Withdrawal)=>formatAdminDate(r.requestedAt)}];return <div><AdminPageHeading eyebrow="Operator profile" title={d.operator.legalName} description={`Plan: ${d.plan?titleCase(d.plan.name):"Unknown"} · joined ${formatAdminDate(d.operator.createdAt)}`}/><EntityNav items={operatorNav(operatorId)}/><div className="mt-7 grid gap-5 lg:grid-cols-2"><Card className="p-6"><Building2 className="size-6 text-primary"/><h2 className="mt-4 font-semibold">Account owner</h2><p className="mt-3 text-sm">{d.user.firstName} {d.user.lastName}<br/>{d.user.email}<br/>{d.user.phone}</p></Card><Card className="p-6"><Landmark className="size-6 text-primary"/><h2 className="mt-4 font-semibold">Settlement</h2><p className="mt-3 text-2xl font-semibold">{formatMoney(d.wallet?.cachedBalance??0)}</p><p className="text-sm text-muted-foreground">Current operator wallet balance</p></Card></div><h2 className="mt-8 text-heading-2 font-semibold">Businesses</h2><DataTable className="mt-4" rows={d.businesses} columns={businessColumns} getRowKey={r=>r.id} caption="Operator businesses"/><h2 className="mt-8 text-heading-2 font-semibold">Withdrawal requests</h2><DataTable className="mt-4" rows={d.withdrawals} columns={withdrawalColumns} getRowKey={r=>r.id} caption="Operator withdrawals" emptyState="No withdrawal requests."/><div className="mt-8"><h2 className="text-heading-2 font-semibold">Compliance history</h2>{d.verification.map((r:VerificationRequest)=><Card key={r.id} className="mt-4 p-5"><div className="flex justify-between"><strong>{r.id}</strong><StatusBadge size="sm" tone={adminTone(r.status)}>{titleCase(r.status)}</StatusBadge></div><p className="mt-2 text-sm text-muted-foreground">{r.notes??"No reviewer notes."}</p></Card>)}</div></div>}
