"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, Clock3, KeyRound, QrCode, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Card, EmptyState, FormField, StatusBadge, formControlClassName } from "@/components/ui";
import { customerActivityRepository } from "@/data";
import { SubmitButton } from "@/features/auth/auth-controls";
import { ActivityLoading, CUSTOMER_ID, PageHeading, formatDate, statusTone, titleCase } from "@/features/customer-activity/activity-ui";

export function CodesScreen() {
  const query = useQuery({ queryKey: ["customer-codes", CUSTOMER_ID], queryFn: () => customerActivityRepository.listCodes(CUSTOMER_ID) });
  return <div><PageHeading eyebrow="Collection security" title="Confirmation codes" description="Use a code only when your water has arrived or you are collecting the order." action={<Link href="/app/codes/confirm" className="inline-flex min-h-control items-center justify-center gap-2 rounded-control bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><KeyRound className="size-4" /> Confirm receipt</Link>} />
    {query.isLoading ? <ActivityLoading /> : query.data && query.data.length > 0 ? <div className="mt-7 grid gap-4 md:grid-cols-2">{query.data.map(({ code, order, business }) => <Link key={code.id} href={`/app/codes/${code.id}`}><Card className="h-full p-5 transition hover:border-primary"><div className="flex items-start justify-between gap-3"><span className="flex size-11 items-center justify-center rounded-control bg-primary-soft text-primary"><QrCode className="size-5" /></span><StatusBadge size="sm" tone={statusTone(code.status)}>{titleCase(code.status)}</StatusBadge></div><p className="mt-5 font-mono text-2xl font-bold tracking-[0.14em]">{code.displayCode}</p><h2 className="mt-3 font-semibold">{business?.name ?? "Water business"}</h2><p className="mt-1 text-sm text-muted-foreground">{order?.orderNumber} · Expires {formatDate(code.expiresAt, true)}</p></Card></Link>)}</div> : <EmptyState className="mt-7" icon={QrCode} title="No confirmation codes" description="Active and redeemed order codes will appear here." />}</div>;
}

export function CodeDetailScreen({ codeId }: { codeId: string }) {
  const query = useQuery({ queryKey: ["customer-code", CUSTOMER_ID, codeId], queryFn: () => customerActivityRepository.findCode(CUSTOMER_ID, codeId) });
  if (query.isLoading) return <ActivityLoading />;
  if (!query.data) return <EmptyState icon={QrCode} title="Code not found" description="This code does not belong to the current customer." action={<Link href="/app/codes" className="font-semibold text-primary">Return to codes</Link>} />;
  const { code, order } = query.data;
  return <div className="mx-auto max-w-3xl"><Link href="/app/codes" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4" /> Back to codes</Link><div className="mt-6 text-center"><StatusBadge tone={statusTone(code.status)}>{titleCase(code.status)}</StatusBadge><h1 className="mt-4 text-heading-1 font-semibold">Order confirmation code</h1><div className="mt-6 rounded-panel border border-primary/25 bg-primary-soft px-6 py-8"><p className="text-xs font-bold tracking-[0.18em] text-info uppercase">Code for {order.order.orderNumber}</p><p className="mt-3 font-mono text-5xl font-bold tracking-[0.18em]">{code.displayCode}</p><p className="mt-4 inline-flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="size-4" /> Expires {formatDate(code.expiresAt, true)}</p></div></div><Card className="mt-6 p-5"><ShieldCheck className="size-5 text-primary" /><h2 className="mt-3 font-semibold">Share only at handover</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">The code closes the order and updates bottle records. Never share it before receiving the correct items.</p><Link href={`/app/orders/${order.order.id}`} className="mt-4 inline-flex text-sm font-semibold text-primary">View order details</Link></Card>{code.status === "ACTIVE" ? <Link href={`/app/codes/confirm?code=${code.displayCode}`} className="mt-6 inline-flex min-h-control w-full items-center justify-center rounded-control bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Confirm this handover</Link> : null}</div>;
}

export function ConfirmCodeScreen({ initialCode = "" }: { initialCode?: string }) {
  const router = useRouter(); const queryClient = useQueryClient(); const [code, setCode] = useState(initialCode); const [error, setError] = useState("");
  const mutation = useMutation({ mutationFn: () => customerActivityRepository.confirmReceipt(CUSTOMER_ID, code), onSuccess: (result) => { queryClient.invalidateQueries({ queryKey: ["customer-codes", CUSTOMER_ID] }); queryClient.invalidateQueries({ queryKey: ["customer-code", CUSTOMER_ID] }); queryClient.invalidateQueries({ queryKey: ["customer-orders", CUSTOMER_ID] }); queryClient.invalidateQueries({ queryKey: ["customer-order", CUSTOMER_ID, result.order.id] }); router.push(`/app/codes/success?orderId=${result.order.id}`); } });
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!/^\d{6}$/.test(code)) { setError("Enter the six-digit confirmation code."); return; } setError(""); mutation.mutate(); }
  return <div className="mx-auto max-w-xl"><Link href="/app/codes" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4" /> Back to codes</Link><PageHeading eyebrow="Secure handover" title="Confirm receipt" description="Confirm only after you have received the correct products and returned any expected empty bottles." /><form onSubmit={submit} noValidate className="mt-7 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="confirmation-code" label="Six-digit code" description="You can find this in your active codes." error={error} required disabled={mutation.isPending}>{(props) => <input {...props} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" className={`${formControlClassName} text-center font-mono text-2xl tracking-[0.25em]`} />}</FormField>{mutation.isError ? <p role="alert" className="mt-4 rounded-control bg-danger-soft px-4 py-3 text-sm font-medium text-danger">{mutation.error.message}</p> : null}<SubmitButton pending={mutation.isPending} className="mt-5"><KeyRound className="size-4" /> Confirm handover</SubmitButton></form></div>;
}

export function CodeSuccessScreen({ orderId }: { orderId?: string }) {
  return <div className="mx-auto max-w-xl text-center"><span className="mx-auto flex size-20 items-center justify-center rounded-full bg-success-soft text-success"><CheckCircle2 className="size-10" /></span><p className="mt-6 text-sm font-semibold text-success">Handover confirmed</p><h1 className="mt-2 text-heading-1 font-semibold">Order completed</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">The confirmation code is redeemed and the delivery and container records are synchronized.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row sm:justify-center">{orderId ? <Link href={`/app/orders/${orderId}/review`} className="inline-flex min-h-control items-center justify-center rounded-control bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Review this order</Link> : null}<Link href="/app/orders/completed" className="inline-flex min-h-control items-center justify-center rounded-control border border-border-strong px-5 py-2.5 text-sm font-semibold">View completed orders</Link></div></div>;
}
