"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Check, Edit3, Mail, MapPin, Phone, Plus, ShieldCheck, Trash2, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Card, ConfirmDialog, EmptyState, FormField, StatusBadge, formControlClassName } from "@/components/ui";
import { addressRepository, customerAccountRepository } from "@/data";
import type { Address } from "@/domain/types";
import { SubmitButton } from "@/features/auth/auth-controls";
import { ActivityLoading, CUSTOMER_ID, PageHeading, formatDate } from "@/features/customer-activity";

export function ProfileScreen() {
  const query = useQuery({ queryKey: ["customer-profile", CUSTOMER_ID], queryFn: () => customerAccountRepository.findProfile(CUSTOMER_ID) });
  if (query.isLoading) return <ActivityLoading />;
  if (!query.data) return <EmptyState icon={UserRound} title="Profile unavailable" description="The customer profile could not be loaded." />;
  const user = query.data;
  return <div><PageHeading eyebrow="Your account" title="Profile" description="Manage your personal information, delivery addresses, and customer resources." action={<Link href="/app/profile/edit" className="inline-flex min-h-control items-center justify-center gap-2 rounded-control bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><Edit3 className="size-4" /> Edit profile</Link>} /><Card className="mt-7 p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="flex size-20 items-center justify-center rounded-full bg-primary-soft text-2xl font-bold text-primary">{user.firstName[0]}{user.lastName[0]}</span><div><h2 className="text-heading-2 font-semibold">{user.firstName} {user.lastName}</h2><div className="mt-2 flex flex-wrap gap-2"><StatusBadge size="sm" tone="success">Active customer</StatusBadge><StatusBadge size="sm" tone={user.isEmailVerified && user.isPhoneVerified ? "success" : "warning"}>{user.isEmailVerified && user.isPhoneVerified ? "Verified" : "Verification needed"}</StatusBadge></div><p className="mt-3 text-sm text-muted-foreground">Customer since {formatDate(user.createdAt)}</p></div></div><dl className="mt-6 grid gap-4 border-t border-border pt-6 sm:grid-cols-2"><div><dt className="text-xs font-semibold text-muted-foreground uppercase">Email</dt><dd className="mt-2 flex items-center gap-2 text-sm"><Mail className="size-4 text-primary" /> {user.email}</dd></div><div><dt className="text-xs font-semibold text-muted-foreground uppercase">Phone</dt><dd className="mt-2 flex items-center gap-2 text-sm"><Phone className="size-4 text-primary" /> {user.phone}</dd></div></dl></Card><div className="mt-6 grid gap-4 sm:grid-cols-2"><Link href="/app/profile/addresses"><Card className="h-full p-5 transition hover:border-primary"><MapPin className="size-5 text-primary" /><h2 className="mt-4 font-semibold">Saved addresses</h2><p className="mt-1 text-sm text-muted-foreground">Manage delivery locations and defaults.</p></Card></Link><Link href="/app/about"><Card className="h-full p-5 transition hover:border-primary"><ShieldCheck className="size-5 text-primary" /><h2 className="mt-4 font-semibold">About and policies</h2><p className="mt-1 text-sm text-muted-foreground">Learn how AquaLoop handles service and data.</p></Card></Link></div></div>;
}

type ProfileErrors = Record<string, string>;
export function EditProfileScreen() {
  const router = useRouter(); const queryClient = useQueryClient(); const [errors, setErrors] = useState<ProfileErrors>({});
  const query = useQuery({ queryKey: ["customer-profile", CUSTOMER_ID], queryFn: () => customerAccountRepository.findProfile(CUSTOMER_ID) });
  const mutation = useMutation({ mutationFn: (input: Parameters<typeof customerAccountRepository.updateProfile>[1]) => customerAccountRepository.updateProfile(CUSTOMER_ID, input), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["customer-profile", CUSTOMER_ID] }); queryClient.invalidateQueries({ queryKey: ["customer-home-discovery", CUSTOMER_ID] }); router.push("/app/profile"); } });
  if (query.isLoading) return <ActivityLoading />; if (!query.data) return <EmptyState title="Profile unavailable" description="Your profile could not be edited." />;
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const input = { firstName:String(data.get("firstName") ?? "").trim(), lastName:String(data.get("lastName") ?? "").trim(), email:String(data.get("email") ?? "").trim(), phone:String(data.get("phone") ?? "").trim() }; const next: ProfileErrors = {}; if (input.firstName.length < 2) next.firstName="Enter your first name."; if (input.lastName.length < 2) next.lastName="Enter your last name."; if (!/^\S+@\S+\.\S+$/.test(input.email)) next.email="Enter a valid email address."; if (!/^\+?[\d\s-]{10,16}$/.test(input.phone)) next.phone="Enter a valid phone number."; setErrors(next); if (Object.keys(next).length === 0) mutation.mutate(input); }
  const user=query.data; return <div className="mx-auto max-w-2xl"><Link href="/app/profile" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4" /> Back to profile</Link><PageHeading eyebrow="Account details" title="Edit profile" description="Changing an email address or phone number marks that field for re-verification." /><form onSubmit={submit} noValidate className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><div className="grid gap-5 sm:grid-cols-2"><FormField id="firstName" label="First name" error={errors.firstName} required disabled={mutation.isPending}>{(props)=><input {...props} name="firstName" defaultValue={user.firstName} autoComplete="given-name" className={formControlClassName} />}</FormField><FormField id="lastName" label="Last name" error={errors.lastName} required disabled={mutation.isPending}>{(props)=><input {...props} name="lastName" defaultValue={user.lastName} autoComplete="family-name" className={formControlClassName} />}</FormField></div><FormField id="email" label="Email address" error={errors.email} required disabled={mutation.isPending}>{(props)=><input {...props} name="email" type="email" defaultValue={user.email} autoComplete="email" className={formControlClassName} />}</FormField><FormField id="phone" label="Phone number" error={errors.phone} required disabled={mutation.isPending}>{(props)=><input {...props} name="phone" type="tel" defaultValue={user.phone} autoComplete="tel" className={formControlClassName} />}</FormField>{mutation.isError ? <p role="alert" className="text-sm font-medium text-danger">{mutation.error.message}</p>:null}<SubmitButton pending={mutation.isPending}>Save profile</SubmitButton></form></div>;
}

export function AddressesScreen() {
  const queryClient=useQueryClient(); const [removeId,setRemoveId]=useState<string|null>(null); const query=useQuery({queryKey:["customer-addresses",CUSTOMER_ID],queryFn:()=>addressRepository.listForOwner(CUSTOMER_ID)}); const defaultMutation=useMutation({mutationFn:(id:string)=>addressRepository.setDefault(CUSTOMER_ID,id),onSuccess:()=>queryClient.invalidateQueries({queryKey:["customer-addresses",CUSTOMER_ID]})}); const removeMutation=useMutation({mutationFn:(id:string)=>addressRepository.removeForOwner(CUSTOMER_ID,id),onSuccess:()=>{setRemoveId(null);queryClient.invalidateQueries({queryKey:["customer-addresses",CUSTOMER_ID]})},onError:()=>setRemoveId(null)});
  return <div><PageHeading eyebrow="Profile" title="Saved addresses" description="Choose a default delivery location and keep reusable addresses current." action={<Link href="/app/profile/addresses/new" className="inline-flex min-h-control items-center justify-center gap-2 rounded-control bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><Plus className="size-4" /> Add address</Link>} />{query.isLoading?<ActivityLoading/>:<div className="mt-7 grid gap-4 md:grid-cols-2">{query.data?.map((address)=><Card key={address.id} className="p-5"><div className="flex justify-between gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-primary-soft text-primary"><MapPin className="size-4" /></span>{address.isDefault?<StatusBadge size="sm" tone="success">Default</StatusBadge>:null}</div><p className="mt-4 text-xs font-bold tracking-wide text-primary uppercase">{address.label}</p><h2 className="mt-2 font-semibold">{address.line1}</h2><p className="mt-1 text-sm text-muted-foreground">{[address.line2,address.city,address.state].filter(Boolean).join(", ")}</p><div className="mt-5 flex flex-wrap gap-4">{!address.isDefault?<button type="button" onClick={()=>defaultMutation.mutate(address.id)} className="inline-flex items-center gap-1 text-sm font-semibold text-primary"><Check className="size-4"/> Make default</button>:null}<Link href={`/app/profile/addresses/${address.id}/edit`} className="text-sm font-semibold text-primary">Edit</Link><button type="button" onClick={()=>setRemoveId(address.id)} className="inline-flex items-center gap-1 text-sm font-semibold text-danger"><Trash2 className="size-4"/> Remove</button></div></Card>)}</div>}{removeMutation.isError?<p role="alert" className="mt-4 text-sm font-medium text-danger">{removeMutation.error.message}</p>:null}<ConfirmDialog open={Boolean(removeId)} onOpenChange={(open)=>!open&&setRemoveId(null)} title="Remove this address?" description="Addresses used by active orders cannot be removed." confirmLabel="Remove address" tone="danger" pending={removeMutation.isPending} onConfirm={()=>removeId&&removeMutation.mutate(removeId)} /></div>;
}

type AddressInput=Pick<Address,"label"|"line1"|"line2"|"city"|"state">;
function AddressForm({initial,onSave,pending,error}:{initial?:AddressInput;onSave:(input:AddressInput)=>void;pending:boolean;error?:string}) { const [errors,setErrors]=useState<Record<string,string>>({}); function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const input={label:String(data.get("label")) as Address["label"],line1:String(data.get("line1")??"").trim(),line2:String(data.get("line2")??"").trim(),city:String(data.get("city")??"").trim(),state:String(data.get("state")??"").trim()};const next:Record<string,string>={};if(input.line1.length<5)next.line1="Enter a complete street address.";if(input.city.length<2)next.city="Enter a city.";if(input.state.length<2)next.state="Enter a state.";setErrors(next);if(Object.keys(next).length===0)onSave(input);} return <form onSubmit={submit} noValidate className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="label" label="Label" required disabled={pending}>{(props)=><select {...props} name="label" defaultValue={initial?.label??"HOME"} className={formControlClassName}><option value="HOME">Home</option><option value="WORK">Work</option><option value="OTHER">Other</option></select>}</FormField><FormField id="line1" label="Street address" error={errors.line1} required disabled={pending}>{(props)=><input {...props} name="line1" defaultValue={initial?.line1} autoComplete="address-line1" className={formControlClassName}/>}</FormField><FormField id="line2" label="Area or landmark" disabled={pending}>{(props)=><input {...props} name="line2" defaultValue={initial?.line2} autoComplete="address-line2" className={formControlClassName}/>}</FormField><div className="grid gap-5 sm:grid-cols-2"><FormField id="city" label="City" error={errors.city} required disabled={pending}>{(props)=><input {...props} name="city" defaultValue={initial?.city} autoComplete="address-level2" className={formControlClassName}/>}</FormField><FormField id="state" label="State" error={errors.state} required disabled={pending}>{(props)=><input {...props} name="state" defaultValue={initial?.state} autoComplete="address-level1" className={formControlClassName}/>}</FormField></div>{error?<p role="alert" className="text-sm font-medium text-danger">{error}</p>:null}<SubmitButton pending={pending}>Save address</SubmitButton></form> }

export function NewAddressProfileScreen(){const router=useRouter();const queryClient=useQueryClient();const mutation=useMutation({mutationFn:(input:AddressInput)=>addressRepository.createForOwner(CUSTOMER_ID,input),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["customer-addresses",CUSTOMER_ID]});router.push("/app/profile/addresses")}});return <div className="mx-auto max-w-2xl"><Link href="/app/profile/addresses" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/> Back to addresses</Link><PageHeading eyebrow="Delivery location" title="Add an address" description="Save a reusable delivery location for future orders."/><AddressForm onSave={(input)=>mutation.mutate(input)} pending={mutation.isPending} error={mutation.error?.message}/></div>}

export function EditAddressProfileScreen({addressId}:{addressId:string}){const router=useRouter();const queryClient=useQueryClient();const query=useQuery({queryKey:["customer-address",CUSTOMER_ID,addressId],queryFn:()=>addressRepository.findForOwner(CUSTOMER_ID,addressId)});const mutation=useMutation({mutationFn:(input:AddressInput)=>addressRepository.updateForOwner(CUSTOMER_ID,addressId,input),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["customer-addresses",CUSTOMER_ID]});queryClient.invalidateQueries({queryKey:["customer-address",CUSTOMER_ID,addressId]});router.push("/app/profile/addresses")}});if(query.isLoading)return <ActivityLoading/>;if(!query.data)return <EmptyState title="Address not found" description="This address does not belong to the current customer."/>;return <div className="mx-auto max-w-2xl"><Link href="/app/profile/addresses" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/> Back to addresses</Link><PageHeading eyebrow={query.data.label} title="Edit address" description="Changes apply to future deliveries; active order snapshots stay unchanged."/><AddressForm initial={query.data} onSave={(input)=>mutation.mutate(input)} pending={mutation.isPending} error={mutation.error?.message}/></div>}
