"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleHelp, Headphones, Mail, Search } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Card, EmptyState, FormField, StatusBadge, formControlClassName } from "@/components/ui";
import { customerAccountRepository } from "@/data";
import { SubmitButton } from "@/features/auth/auth-controls";
import { ActivityLoading, CUSTOMER_ID, PageHeading, titleCase } from "@/features/customer-activity";

export function SupportScreen() {
  const [search,setSearch]=useState(""); const query=useQuery({queryKey:["support-articles"],queryFn:()=>customerAccountRepository.listSupportArticles()}); const articles=query.data?.filter((item)=>`${item.title} ${item.summary} ${item.category}`.toLowerCase().includes(search.toLowerCase()))??[];
  return <div><PageHeading eyebrow="Customer help" title="Support centre" description="Browse practical guidance or send the support team a message." action={<Link href="/app/support/contact" className="inline-flex min-h-control items-center justify-center gap-2 rounded-control bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><Headphones className="size-4"/> Contact support</Link>}/><label className="relative mt-7 block"><span className="sr-only">Search support articles</span><Search className="absolute top-1/2 left-4 size-4 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search payments, delivery, account..." className={`${formControlClassName} pl-11`}/></label>{query.isLoading?<ActivityLoading/>:articles.length>0?<div className="mt-6 grid gap-4 md:grid-cols-2">{articles.map((article)=><Link key={article.id} href={`/app/support/${article.id}`}><Card className="h-full p-5 transition hover:border-primary"><StatusBadge size="sm" tone="info">{titleCase(article.category)}</StatusBadge><h2 className="mt-4 font-semibold">{article.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{article.summary}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary">Read article <ArrowRight className="size-4"/></span></Card></Link>)}</div>:<EmptyState className="mt-6" icon={CircleHelp} title="No matching help articles" description="Try another search or contact customer support."/>}<Card className="mt-7 flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><h2 className="font-semibold">Still need help?</h2><p className="mt-1 text-sm text-muted-foreground">Send a message with an order number when relevant.</p></div><Link href="/app/support/contact" className="text-sm font-semibold text-primary">Contact support</Link></Card></div>;
}

export function SupportArticleScreen({articleId}:{articleId:string}) { const query=useQuery({queryKey:["support-article",articleId],queryFn:()=>customerAccountRepository.findSupportArticle(articleId)});if(query.isLoading)return <ActivityLoading/>;if(!query.data)return <EmptyState icon={CircleHelp} title="Article not found" description="This support article is unavailable." action={<Link href="/app/support" className="font-semibold text-primary">Return to support</Link>}/>;const article=query.data;return <article className="mx-auto max-w-3xl"><Link href="/app/support" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/> Back to support</Link><div className="mt-6 rounded-panel border border-border bg-surface p-6 shadow-card sm:p-8"><StatusBadge tone="info">{titleCase(article.category)}</StatusBadge><h1 className="mt-4 text-heading-1 font-semibold">{article.title}</h1><p className="mt-3 text-base leading-7 text-muted-foreground">{article.summary}</p><div className="my-7 border-t border-border"/><p className="leading-8 text-foreground">{article.body}</p></div><Link href="/app/support/contact" className="mt-5 inline-flex min-h-control items-center gap-2 rounded-control bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground"><Headphones className="size-4"/> Contact support about this</Link></article> }

export function ContactSupportScreen(){const queryClient=useQueryClient();const [errors,setErrors]=useState<Record<string,string>>({});const [reference,setReference]=useState("");const mutation=useMutation({mutationFn:(input:{subject:string;message:string})=>customerAccountRepository.contactSupport(CUSTOMER_ID,input),onSuccess:(value)=>{setReference(value);queryClient.invalidateQueries({queryKey:["customer-notifications",CUSTOMER_ID]})}});function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const input={subject:String(data.get("subject")??"").trim(),message:String(data.get("message")??"").trim()};const next:Record<string,string>={};if(input.subject.length<5)next.subject="Enter a clear subject.";if(input.message.length<20)next.message="Describe the issue in at least 20 characters.";setErrors(next);if(Object.keys(next).length===0)mutation.mutate(input)}if(reference)return <div className="mx-auto max-w-xl text-center"><CheckCircle2 className="mx-auto size-16 text-success"/><p className="mt-5 text-sm font-semibold text-success">Message received</p><h1 className="mt-2 text-heading-1 font-semibold">We’ll take a look</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Support reference <strong className="font-mono text-foreground">{reference}</strong> has been added to your notifications.</p><Link href="/app/notifications" className="mt-6 inline-flex min-h-control items-center rounded-control bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">View notifications</Link></div>;return <div className="mx-auto max-w-2xl"><Link href="/app/support" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/> Back to support</Link><PageHeading eyebrow="Customer support" title="Contact us" description="Include an order number and the outcome you need. This demo stores no attachments."/><form onSubmit={submit} noValidate className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="subject" label="Subject" error={errors.subject} required disabled={mutation.isPending}>{(props)=><input {...props} name="subject" className={formControlClassName}/>}</FormField><FormField id="message" label="How can we help?" error={errors.message} required disabled={mutation.isPending}>{(props)=><textarea {...props} name="message" rows={6} className={`${formControlClassName} resize-y`}/>}</FormField>{mutation.isError?<p role="alert" className="text-sm font-medium text-danger">{mutation.error.message}</p>:null}<SubmitButton pending={mutation.isPending}><Mail className="size-4"/> Send message</SubmitButton></form></div>}
