"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Edit3, Package, PanelsTopLeft, Plus } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";

import { Card, DataTable, EmptyState, FormField, StatusBadge, formControlClassName } from "@/components/ui";
import { adminOperationsRepository } from "@/data";
import type { Plan, Product } from "@/domain/types";
import { SubmitButton } from "@/features/auth/auth-controls";
import { AdminLoading, AdminPageHeading, adminActionClassName, titleCase } from "@/features/admin-accounts";
import { formatMoney } from "@/lib/money";

export function ProductsAdminScreen(){const query=useQuery({queryKey:["admin-products"],queryFn:()=>adminOperationsRepository.products()});const columns=[{id:"product",header:"Product",cell:(r:Product)=><div><strong>{r.name}</strong><p className="mt-1 text-xs text-muted-foreground">{r.slug}</p></div>},{id:"type",header:"Type",cell:(r:Product)=>titleCase(r.type)},{id:"size",header:"Size",align:"right" as const,cell:(r:Product)=>`${r.sizeLitres}L`},{id:"status",header:"Status",cell:(r:Product)=><StatusBadge size="sm" tone={r.active?"success":"danger"}>{r.active?"Active":"Inactive"}</StatusBadge>},{id:"action",header:"",align:"right" as const,cell:(r:Product)=><Link href={`/admin/products/${r.id}/edit`} className="inline-flex items-center gap-1 font-semibold text-primary"><Edit3 className="size-4"/>Edit</Link>}];return <div><AdminPageHeading eyebrow="Platform catalogue" title="Products" description="Manage the canonical refill and bottle-exchange products available to businesses." action={<Link href="/admin/products/new" className={adminActionClassName}><Plus className="size-4"/>New product</Link>}/>{query.isLoading?<AdminLoading/>:<DataTable className="mt-7" rows={query.data??[]} columns={columns} getRowKey={r=>r.id} caption="Product catalogue"/>}</div>}

export function ProductFormScreen({productId}:{productId?:string}){const router=useRouter();const client=useQueryClient();const query=useQuery({enabled:Boolean(productId),queryKey:["admin-product",productId],queryFn:()=>adminOperationsRepository.product(productId!)});const mutation=useMutation({mutationFn:(input:Omit<Product,"id"|"slug">)=>adminOperationsRepository.saveProduct(productId??null,input),onSuccess:()=>{client.invalidateQueries({queryKey:["admin-products"]});router.push("/admin/products")}});if(productId&&query.isLoading)return <AdminLoading/>;if(productId&&!query.data)return <EmptyState icon={Package} title="Product not found" description="This product cannot be edited."/>;const product=query.data;function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mutation.mutate({name:String(d.get("name")??""),sizeLitres:Number(d.get("sizeLitres")),type:String(d.get("type")) as Product["type"],description:String(d.get("description")??""),imageUrl:String(d.get("imageUrl")??""),active:d.get("active")==="on"});}return <div className="mx-auto max-w-2xl"><AdminPageHeading eyebrow="Product catalogue" title={product?"Edit product":"New product"} description="Product names generate stable URL slugs; existing business pricing remains separate."/><form onSubmit={submit} className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="product-name" label="Product name" required>{p=><input {...p} name="name" defaultValue={product?.name} className={formControlClassName}/>}</FormField><div className="grid gap-5 sm:grid-cols-2"><FormField id="product-size" label="Size in litres" required>{p=><input {...p} name="sizeLitres" type="number" min="1" max="100" defaultValue={product?.sizeLitres??20} className={formControlClassName}/>}</FormField><FormField id="product-type" label="Product type" required>{p=><select {...p} name="type" defaultValue={product?.type??"REFILL"} className={formControlClassName}><option value="REFILL">Refill</option><option value="BOTTLE_EXCHANGE">Bottle exchange</option></select>}</FormField></div><FormField id="product-description" label="Description" required>{p=><textarea {...p} name="description" defaultValue={product?.description} rows={4} className={`${formControlClassName} resize-y`}/>}</FormField><FormField id="product-image" label="Image path" required>{p=><input {...p} name="imageUrl" defaultValue={product?.imageUrl??"/images/products/new-product.png"} className={formControlClassName}/>}</FormField><label className="flex items-center gap-3 text-sm font-semibold"><input name="active" type="checkbox" defaultChecked={product?.active??true} className="size-4 accent-primary"/>Active in platform catalogue</label>{mutation.isError?<p role="alert" className="text-sm text-danger">{mutation.error.message}</p>:null}<SubmitButton pending={mutation.isPending}>Save product</SubmitButton></form></div>}

export function PlansAdminScreen(){const query=useQuery({queryKey:["admin-plans"],queryFn:()=>adminOperationsRepository.plans()});return <div><AdminPageHeading eyebrow="Commercial catalogue" title="Plans" description="Configure operator subscription fees, settlement rates, business limits, and analytics retention." action={<Link href="/admin/plans/new" className={adminActionClassName}><Plus className="size-4"/>New plan</Link>}/>{query.isLoading?<AdminLoading/>:<div className="mt-7 grid gap-4 lg:grid-cols-3">{query.data?.map(plan=><Card key={plan.id} className="p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">{titleCase(plan.name)}</h2><StatusBadge size="sm" tone={plan.active?"success":"danger"}>{plan.active?"Active":"Inactive"}</StatusBadge></div><p className="mt-4 text-3xl font-semibold">{formatMoney(plan.monthlyFee)}</p><p className="mt-4 text-sm text-muted-foreground">{plan.settlementFeePercent}% settlement · {plan.maxBusinesses} businesses · {plan.analyticsRetentionDays} analytics days</p><Link href={`/admin/plans/${plan.id}/edit`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary"><Edit3 className="size-4"/>Edit plan</Link></Card>)}</div>}</div>}

export function PlanFormScreen({planId}:{planId?:string}){const router=useRouter();const client=useQueryClient();const query=useQuery({enabled:Boolean(planId),queryKey:["admin-plan",planId],queryFn:()=>adminOperationsRepository.plan(planId!)});const mutation=useMutation({mutationFn:(input:Omit<Plan,"id">)=>adminOperationsRepository.savePlan(planId??null,input),onSuccess:()=>{client.invalidateQueries({queryKey:["admin-plans"]});client.invalidateQueries({queryKey:["operator-plans"]});router.push("/admin/plans")}});if(planId&&query.isLoading)return <AdminLoading/>;if(planId&&!query.data)return <EmptyState icon={PanelsTopLeft} title="Plan not found" description="This plan cannot be edited."/>;const plan=query.data;function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mutation.mutate({name:String(d.get("name")??""),monthlyFee:Math.round(Number(d.get("monthlyFee"))*100),settlementFeePercent:Number(d.get("settlementFeePercent")),maxBusinesses:Number(d.get("maxBusinesses")),analyticsRetentionDays:Number(d.get("analyticsRetentionDays")),active:d.get("active")==="on"});}return <div className="mx-auto max-w-2xl"><AdminPageHeading eyebrow="Operator subscriptions" title={plan?"Edit plan":"New plan"} description="Amounts are entered in GBP and stored as integer minor units."/><form onSubmit={submit} className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="plan-name" label="Plan name" required>{p=><input {...p} name="name" defaultValue={plan?.name} className={formControlClassName}/>}</FormField><div className="grid gap-5 sm:grid-cols-2"><FormField id="plan-fee" label="Monthly fee in GBP" required>{p=><input {...p} name="monthlyFee" type="number" min="0" step="0.01" defaultValue={(plan?.monthlyFee??0)/100} className={formControlClassName}/>}</FormField><FormField id="plan-settlement" label="Settlement fee percentage" required>{p=><input {...p} name="settlementFeePercent" type="number" min="0" max="100" step="0.1" defaultValue={plan?.settlementFeePercent??2} className={formControlClassName}/>}</FormField><FormField id="plan-businesses" label="Maximum businesses" required>{p=><input {...p} name="maxBusinesses" type="number" min="1" defaultValue={plan?.maxBusinesses??1} className={formControlClassName}/>}</FormField><FormField id="plan-retention" label="Analytics retention days" required>{p=><input {...p} name="analyticsRetentionDays" type="number" min="1" defaultValue={plan?.analyticsRetentionDays??30} className={formControlClassName}/>}</FormField></div><label className="flex items-center gap-3 text-sm font-semibold"><input name="active" type="checkbox" defaultChecked={plan?.active??true} className="size-4 accent-primary"/>Available to operators</label>{mutation.isError?<p role="alert" className="text-sm text-danger">{mutation.error.message}</p>:null}<SubmitButton pending={mutation.isPending}>Save plan</SubmitButton></form></div>}
