"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Ban, Bell, CheckCircle2, Plus, Sparkles, Star } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Card, ConfirmDialog, DataTable, FormField, StatusBadge, formControlClassName } from "@/components/ui";
import { adminOperationsRepository } from "@/data";
import type { BlocklistEntry, CleanupRun, Notification } from "@/domain/types";
import { SubmitButton } from "@/features/auth/auth-controls";
import { AdminLoading, AdminPageHeading, MetricGrid, adminActionClassName, adminSecondaryClassName, formatAdminDate, titleCase } from "@/features/admin-accounts";

type NotificationRow=Awaited<ReturnType<typeof adminOperationsRepository.notifications>>[number];type RatingRow=Awaited<ReturnType<typeof adminOperationsRepository.ratings>>[number];
export function AdminNotificationsScreen(){const query=useQuery({queryKey:["admin-notifications"],queryFn:()=>adminOperationsRepository.notifications()});const columns=[{id:"message",header:"Message",cell:(r:NotificationRow)=><div><strong>{r.notification.title}</strong><p className="mt-1 max-w-xl text-xs text-muted-foreground">{r.notification.body}</p></div>},{id:"recipient",header:"Recipient",cell:(r:NotificationRow)=>r.user?`${r.user.firstName} ${r.user.lastName}`:r.notification.userId},{id:"channel",header:"Channel",cell:(r:NotificationRow)=>titleCase(r.notification.channel)},{id:"status",header:"Status",cell:(r:NotificationRow)=><StatusBadge size="sm" tone={r.notification.read?"neutral":"info"}>{r.notification.read?"Read":"Unread"}</StatusBadge>},{id:"date",header:"Created",cell:(r:NotificationRow)=>formatAdminDate(r.notification.createdAt,true)}];return <div><AdminPageHeading eyebrow="Platform communications" title="Notifications" description="Audit customer and operator notifications across all delivery channels." action={<Link href="/admin/notifications/new" className={adminActionClassName}><Plus className="size-4"/>New notification</Link>}/>{query.isLoading?<AdminLoading/>:<DataTable className="mt-7" rows={query.data??[]} columns={columns} getRowKey={r=>r.notification.id} caption="Platform notifications"/>}</div>}

export function NewAdminNotificationScreen(){const router=useRouter();const client=useQueryClient();const [sent,setSent]=useState<number|null>(null);const mutation=useMutation({mutationFn:(input:Parameters<typeof adminOperationsRepository.createNotification>[0])=>adminOperationsRepository.createNotification(input),onSuccess:count=>{setSent(count);client.invalidateQueries({queryKey:["admin-notifications"]});setTimeout(()=>router.push("/admin/notifications"),900)}});function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mutation.mutate({audience:String(d.get("audience")) as "CUSTOMERS"|"OPERATORS"|"ALL",title:String(d.get("title")??""),body:String(d.get("body")??""),channel:String(d.get("channel")) as Notification["channel"],type:String(d.get("type")) as Notification["type"]});}return <div className="mx-auto max-w-2xl"><AdminPageHeading eyebrow="Platform communications" title="Create notification" description="A separate notification record is created for every eligible recipient in the selected audience."/><form onSubmit={submit} className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><div className="grid gap-5 sm:grid-cols-2"><FormField id="notification-audience" label="Audience" required>{p=><select {...p} name="audience" className={formControlClassName}><option value="CUSTOMERS">All customers</option><option value="OPERATORS">All operators</option><option value="ALL">All users</option></select>}</FormField><FormField id="notification-channel" label="Channel" required>{p=><select {...p} name="channel" className={formControlClassName}><option value="IN_APP">In app</option><option value="EMAIL">Email</option><option value="SMS">SMS</option><option value="PUSH">Push</option></select>}</FormField></div><FormField id="notification-type" label="Notification type" required>{p=><select {...p} name="type" className={formControlClassName}>{["SYSTEM","ACCOUNT","ORDER","PAYMENT","DELIVERY","PROMOTION"].map(value=><option key={value} value={value}>{titleCase(value)}</option>)}</select>}</FormField><FormField id="notification-title" label="Title" required>{p=><input {...p} name="title" className={formControlClassName}/>}</FormField><FormField id="notification-body" label="Message" required>{p=><textarea {...p} name="body" rows={5} className={`${formControlClassName} resize-y`}/>}</FormField>{mutation.isError?<p role="alert" className="text-sm text-danger">{mutation.error.message}</p>:null}{sent!==null?<p role="status" className="inline-flex items-center gap-2 text-sm font-semibold text-success"><CheckCircle2 className="size-4"/>Created {sent} notifications.</p>:null}<SubmitButton pending={mutation.isPending}><Bell className="size-4"/>Send notification</SubmitButton></form></div>}

export function BlocklistScreen(){const client=useQueryClient();const query=useQuery({queryKey:["admin-blocklist"],queryFn:()=>adminOperationsRepository.blocklist()});const [target,setTarget]=useState<BlocklistEntry|null>(null);const mutation=useMutation({mutationFn:(id:string)=>adminOperationsRepository.toggleBlocklist(id),onSuccess:()=>{setTarget(null);client.invalidateQueries({queryKey:["admin-blocklist"]})}});const columns=[{id:"value",header:"Blocked value",cell:(r:BlocklistEntry)=><div><strong>{r.value}</strong><p className="mt-1 text-xs text-muted-foreground">{titleCase(r.type)}</p></div>},{id:"reason",header:"Reason",cell:(r:BlocklistEntry)=><p className="max-w-lg">{r.reason}</p>},{id:"status",header:"Status",cell:(r:BlocklistEntry)=><StatusBadge size="sm" tone={r.active?"danger":"neutral"}>{r.active?"Active":"Inactive"}</StatusBadge>},{id:"date",header:"Created",cell:(r:BlocklistEntry)=>formatAdminDate(r.createdAt)},{id:"action",header:"",align:"right" as const,cell:(r:BlocklistEntry)=><button onClick={()=>setTarget(r)} className="font-semibold text-primary">{r.active?"Deactivate":"Reactivate"}</button>}];return <div><AdminPageHeading eyebrow="Trust and safety" title="Blocklist" description="Prevent known email addresses and phone numbers from being reused for platform registration." action={<Link href="/admin/blocklist/new" className={adminActionClassName}><Plus className="size-4"/>New entry</Link>}/>{query.isLoading?<AdminLoading/>:<DataTable className="mt-7" rows={query.data??[]} columns={columns} getRowKey={r=>r.id} caption="Registration blocklist"/>}<ConfirmDialog open={Boolean(target)} onOpenChange={open=>!open&&setTarget(null)} title={`${target?.active?"Deactivate":"Reactivate"} this entry?`} description="The original audit record and reason remain available." confirmLabel="Confirm change" pending={mutation.isPending} onConfirm={()=>target&&mutation.mutate(target.id)}/></div>}

export function NewBlocklistScreen(){const router=useRouter();const client=useQueryClient();const mutation=useMutation({mutationFn:(input:Pick<BlocklistEntry,"type"|"value"|"reason">)=>adminOperationsRepository.createBlocklist(input),onSuccess:()=>{client.invalidateQueries({queryKey:["admin-blocklist"]});router.push("/admin/blocklist")}});function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mutation.mutate({type:String(d.get("type")) as BlocklistEntry["type"],value:String(d.get("value")??""),reason:String(d.get("reason")??"")});}return <div className="mx-auto max-w-xl"><AdminPageHeading eyebrow="Registration protection" title="New blocklist entry" description="Add an email address or phone number with a clear administrative reason."/><form onSubmit={submit} className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="block-type" label="Identifier type" required>{p=><select {...p} name="type" className={formControlClassName}><option value="EMAIL">Email</option><option value="PHONE">Phone</option></select>}</FormField><FormField id="block-value" label="Email or phone value" required>{p=><input {...p} name="value" className={formControlClassName}/>}</FormField><FormField id="block-reason" label="Administrative reason" required>{p=><textarea {...p} name="reason" rows={4} className={`${formControlClassName} resize-y`}/>}</FormField>{mutation.isError?<p role="alert" className="text-sm text-danger">{mutation.error.message}</p>:null}<SubmitButton pending={mutation.isPending}><Ban className="size-4"/>Add to blocklist</SubmitButton></form></div>}

export function AdminRatingsScreen(){const query=useQuery({queryKey:["admin-ratings"],queryFn:()=>adminOperationsRepository.ratings()});const rows=query.data??[];const average=rows.length?rows.reduce((s,r)=>s+r.review.rating,0)/rows.length:0;const columns=[{id:"rating",header:"Rating",cell:(r:RatingRow)=><span className="inline-flex items-center gap-1 font-semibold text-warning"><Star className="size-4 fill-warning"/>{r.review.rating}/5</span>},{id:"customer",header:"Customer",cell:(r:RatingRow)=>r.customer?<Link href={`/admin/customers/${r.customer.id}`} className="font-semibold text-primary">{r.customer.firstName} {r.customer.lastName}</Link>:r.review.customerId},{id:"business",header:"Business",cell:(r:RatingRow)=>r.business?<Link href={`/admin/businesses/${r.business.id}/ratings`} className="font-semibold text-primary">{r.business.name}</Link>:r.review.businessId},{id:"review",header:"Review",cell:(r:RatingRow)=><p className="max-w-lg">{r.review.body}</p>},{id:"date",header:"Created",cell:(r:RatingRow)=>formatAdminDate(r.review.createdAt)}];return <div><AdminPageHeading eyebrow="Quality monitoring" title="Platform ratings" description="Review customer feedback across every business and completed-order record."/><MetricGrid items={[{label:"Average rating",value:average.toFixed(1)},{label:"Reviews",value:rows.length},{label:"Five-star reviews",value:rows.filter(r=>r.review.rating===5).length},{label:"Businesses reviewed",value:new Set(rows.map(r=>r.review.businessId)).size}]}/>{query.isLoading?<AdminLoading/>:<DataTable className="mt-7" rows={rows} columns={columns} getRowKey={r=>r.review.id} caption="Platform ratings"/>}</div>}

export function CleanupScreen(){const client=useQueryClient();const query=useQuery({queryKey:["admin-cleanup-runs"],queryFn:()=>adminOperationsRepository.cleanupRuns()});const [scope,setScope]=useState<CleanupRun["scope"]|null>(null);const mutation=useMutation({mutationFn:(value:CleanupRun["scope"])=>adminOperationsRepository.runCleanup(value),onSuccess:()=>{setScope(null);client.invalidateQueries({queryKey:["admin-cleanup-runs"]});client.invalidateQueries({queryKey:["admin-notifications"]});client.invalidateQueries({queryKey:["admin-operations-orders"]})}});const options=[{scope:"EXPIRED_CODES" as const,title:"Expire old confirmation codes",description:"Mark active or issued codes past their expiry timestamp as expired."},{scope:"READ_NOTIFICATIONS" as const,title:"Remove old read notifications",description:"Delete read notifications older than seven days."},{scope:"STALE_DRAFTS" as const,title:"Cancel stale draft orders",description:"Cancel draft orders with no update in the last 24 hours."}];return <div><AdminPageHeading eyebrow="Platform maintenance" title="System cleanup" description="Run narrow, audited cleanup jobs. Every run records its scope, administrator, time, and affected rows."/><div className="mt-7 grid gap-4 lg:grid-cols-3">{options.map(option=><Card key={option.scope} className="flex flex-col p-6"><Sparkles className="size-5 text-primary"/><h2 className="mt-4 font-semibold">{option.title}</h2><p className="mt-2 flex-1 text-sm leading-6 text-muted-foreground">{option.description}</p><button onClick={()=>setScope(option.scope)} className={`${adminSecondaryClassName} mt-5`}>Preview and run</button></Card>)}</div><h2 className="mt-8 text-heading-2 font-semibold">Cleanup history</h2><div className="mt-4 space-y-3">{query.data?.map(run=><Card key={run.id} className="flex justify-between gap-4 p-5"><div><strong>{titleCase(run.scope)}</strong><p className="mt-1 text-sm text-muted-foreground">{formatAdminDate(run.runAt,true)} · {run.adminId}</p></div><StatusBadge tone="info">{run.affectedRows} affected</StatusBadge></Card>)}</div><ConfirmDialog open={Boolean(scope)} onOpenChange={open=>!open&&setScope(null)} title={`Run ${scope?titleCase(scope):"cleanup"}?`} description="Only the selected record type will be changed. The result will be written to cleanup history." confirmLabel="Run cleanup" tone="danger" pending={mutation.isPending} onConfirm={()=>scope&&mutation.mutate(scope)}/></div>}
