"use client";

import { BadgeCheck, Building2, FileCheck2, MapPin, ShieldCheck, Truck, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Card, FormField, formControlClassName } from "@/components/ui";
import type { FulfilmentMode } from "@/domain/types";
import { SubmitButton } from "@/features/auth/auth-controls";
import { FlowGuard, FlowHeading } from "@/features/operator-onboarding/flow-ui";
import { useOperatorOnboarding } from "@/features/operator-onboarding/onboarding-provider";

function FlowCard({children}:{children:React.ReactNode}){return <div className="mx-auto max-w-3xl rounded-panel border border-border bg-surface p-6 shadow-card sm:p-8">{children}</div>}
function Back({href}:{href:string}){return <Link href={href} className="text-sm font-semibold text-primary">← Back</Link>}

export function OperatorOnboardingScreen(){const {draft}=useOperatorOnboarding();if(!draft.accountVerified)return <FlowGuard title="Verify the operator account" description="Account verification is required before onboarding." href="/operator/register" label="Start registration"/>;const steps=[[UserRound,"Identity","Legal and trading names"],[FileCheck2,"Compliance","Registration and document references"],[MapPin,"Location","Primary operating address"],[Truck,"Fulfilment","Delivery and pickup choices"]] as const;return <FlowCard><FlowHeading eyebrow="Operator onboarding" title="Prepare your operator profile" description="Complete four short sections before creating the first business."/><div className="mt-7 grid gap-4 sm:grid-cols-2">{steps.map(([Icon,title,body],index)=><Card key={title} className="p-5"><Icon className="size-5 text-primary"/><p className="mt-4 text-xs font-bold text-primary">0{index+1}</p><h2 className="mt-1 font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{body}</p></Card>)}</div><Link href="/operator/onboarding/identity" className="mt-7 inline-flex min-h-control w-full items-center justify-center rounded-control bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Begin onboarding</Link></FlowCard>}

export function OperatorIdentityScreen(){const router=useRouter();const {draft,update}=useOperatorOnboarding();const [errors,setErrors]=useState<Record<string,string>>({});function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const legalName=String(data.get("legalName")??"").trim();const tradingName=String(data.get("tradingName")??"").trim();const next:Record<string,string>={};if(legalName.length<4)next.legalName="Enter the registered legal name.";if(tradingName.length<2)next.tradingName="Enter the trading name.";setErrors(next);if(Object.keys(next).length===0){update({legalName,tradingName});router.push("/operator/onboarding/compliance")}}return <FlowCard><Back href="/operator/onboarding"/><FlowHeading eyebrow="Step 1 of 4" title="Operator identity" description="Use the legal entity that owns or operates the water business."/><form onSubmit={submit} className="mt-7 space-y-5" noValidate><FormField id="legalName" label="Registered legal name" error={errors.legalName} required>{(props)=><input {...props} name="legalName" defaultValue={draft.legalName} className={formControlClassName}/>}</FormField><FormField id="tradingName" label="Trading name" error={errors.tradingName} required>{(props)=><input {...props} name="tradingName" defaultValue={draft.tradingName} className={formControlClassName}/>}</FormField><SubmitButton>Continue to compliance</SubmitButton></form></FlowCard>}

export function OperatorComplianceScreen(){const router=useRouter();const {draft,update}=useOperatorOnboarding();const [errors,setErrors]=useState<Record<string,string>>({});function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const registrationNumber=String(data.get("registrationNumber")??"").trim();const identityDocumentLabel=String(data.get("identityDocumentLabel")??"").trim();const complianceDocumentLabel=String(data.get("complianceDocumentLabel")??"").trim();const next:Record<string,string>={};if(registrationNumber.length<5)next.registrationNumber="Enter a valid registration reference.";if(identityDocumentLabel.length<5)next.identityDocumentLabel="Enter an identity document label.";if(complianceDocumentLabel.length<5)next.complianceDocumentLabel="Enter a compliance document label.";setErrors(next);if(Object.keys(next).length===0){update({registrationNumber,identityDocumentLabel,complianceDocumentLabel});router.push("/operator/onboarding/location")}}return <FlowCard><Back href="/operator/onboarding/identity"/><FlowHeading eyebrow="Step 2 of 4" title="Compliance references" description="This prototype records safe document labels only; no identity or certificate contents are uploaded."/><form onSubmit={submit} className="mt-7 space-y-5" noValidate><FormField id="registrationNumber" label="Company registration number" error={errors.registrationNumber} required>{(props)=><input {...props} name="registrationNumber" defaultValue={draft.registrationNumber} placeholder="RC-123456" className={formControlClassName}/>}</FormField><FormField id="identityDocumentLabel" label="Identity document label" description="For example: director-id.pdf" error={errors.identityDocumentLabel} required>{(props)=><input {...props} name="identityDocumentLabel" defaultValue={draft.identityDocumentLabel} className={formControlClassName}/>}</FormField><FormField id="complianceDocumentLabel" label="Water-quality certificate label" description="For example: quality-certificate.pdf" error={errors.complianceDocumentLabel} required>{(props)=><input {...props} name="complianceDocumentLabel" defaultValue={draft.complianceDocumentLabel} className={formControlClassName}/>}</FormField><SubmitButton><FileCheck2 className="size-4"/> Save compliance references</SubmitButton></form></FlowCard>}

export function OperatorLocationScreen(){const router=useRouter();const {draft,update}=useOperatorOnboarding();const [errors,setErrors]=useState<Record<string,string>>({});function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const location={line1:String(data.get("line1")??"").trim(),line2:String(data.get("line2")??"").trim(),city:String(data.get("city")??"").trim(),state:String(data.get("state")??"").trim()};const next:Record<string,string>={};if(location.line1.length<5)next.line1="Enter a complete street address.";if(location.city.length<2)next.city="Enter a city.";if(location.state.length<2)next.state="Enter a state.";setErrors(next);if(Object.keys(next).length===0){update({location});router.push("/operator/onboarding/delivery")}}return <FlowCard><Back href="/operator/onboarding/compliance"/><FlowHeading eyebrow="Step 3 of 4" title="Primary operating location" description="This address seeds the first business and can be adjusted during business creation."/><form onSubmit={submit} className="mt-7 space-y-5"><FormField id="line1" label="Street address" error={errors.line1} required>{(props)=><input {...props} name="line1" defaultValue={draft.location.line1} autoComplete="address-line1" className={formControlClassName}/>}</FormField><FormField id="line2" label="Area or landmark">{(props)=><input {...props} name="line2" defaultValue={draft.location.line2} autoComplete="address-line2" className={formControlClassName}/>}</FormField><div className="grid gap-5 sm:grid-cols-2"><FormField id="city" label="City" error={errors.city} required>{(props)=><input {...props} name="city" defaultValue={draft.location.city} className={formControlClassName}/>}</FormField><FormField id="state" label="State" error={errors.state} required>{(props)=><input {...props} name="state" defaultValue={draft.location.state} className={formControlClassName}/>}</FormField></div><SubmitButton><MapPin className="size-4"/> Save location</SubmitButton></form></FlowCard>}

export function OperatorDeliveryScreen(){const router=useRouter();const {draft,update}=useOperatorOnboarding();const [modes,setModes]=useState<FulfilmentMode[]>(draft.fulfilmentModes);const [radius,setRadius]=useState(draft.deliveryRadiusKm);const [error,setError]=useState("");function toggle(mode:FulfilmentMode){setModes((current)=>current.includes(mode)?current.filter((item)=>item!==mode):[...current,mode])}function submit(){if(modes.length===0){setError("Choose delivery, pickup, or both.");return}if(modes.includes("DELIVERY")&&(radius<1||radius>50)){setError("Delivery radius must be between 1 and 50 km.");return}update({fulfilmentModes:modes,deliveryRadiusKm:modes.includes("DELIVERY")?radius:0});router.push("/operator/onboarding/complete")}return <FlowCard><Back href="/operator/onboarding/location"/><FlowHeading eyebrow="Step 4 of 4" title="Fulfilment options" description="Choose how customers can receive orders from your business."/><div className="mt-7 grid gap-4 sm:grid-cols-2">{([["DELIVERY",Truck,"Doorstep delivery"],["PICKUP",Building2,"Business pickup"]] as const).map(([mode,Icon,label])=><button key={mode} type="button" onClick={()=>toggle(mode)} className={`rounded-card border p-5 text-left ${modes.includes(mode)?"border-primary bg-primary-soft/40 ring-3 ring-primary/10":"border-border"}`}><Icon className="size-5 text-primary"/><span className="mt-4 block font-semibold">{label}</span>{modes.includes(mode)?<span className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-success"><BadgeCheck className="size-4"/> Selected</span>:null}</button>)}</div>{modes.includes("DELIVERY")?<FormField id="deliveryRadius" label="Delivery radius (km)" description="Between 1 and 50 km.">{(props)=><input {...props} type="number" min="1" max="50" value={radius} onChange={(event)=>setRadius(Number(event.target.value))} className={`${formControlClassName} mt-5`}/>}</FormField>:null}{error?<p role="alert" className="mt-4 text-sm font-medium text-danger">{error}</p>:null}<button type="button" onClick={submit} className="mt-6 inline-flex min-h-control w-full items-center justify-center rounded-control bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Complete operator profile</button></FlowCard>}

export function OperatorOnboardingCompleteScreen(){const {draft}=useOperatorOnboarding();const ready=draft.legalName&&draft.registrationNumber&&draft.location.line1&&draft.fulfilmentModes.length>0;if(!ready)return <FlowGuard title="Operator profile is incomplete" description="Complete identity, compliance, location, and fulfilment first." href="/operator/onboarding" label="Resume onboarding"/>;return <FlowCard><div className="text-center"><span className="mx-auto flex size-16 items-center justify-center rounded-full bg-success-soft text-success"><ShieldCheck className="size-8"/></span><p className="mt-5 text-sm font-semibold text-success">Operator profile complete</p><h1 className="mt-2 text-heading-1 font-semibold">Create your first business</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{draft.legalName} can now add its customer-facing business profile.</p></div><div className="mt-7 rounded-card bg-surface-muted p-5"><p className="text-sm font-semibold">{draft.tradingName}</p><p className="mt-1 text-sm text-muted-foreground">{draft.location.city}, {draft.location.state} · {draft.fulfilmentModes.map((mode)=>mode.toLowerCase()).join(" and ")}</p></div><Link href="/operator/businesses/new" className="mt-6 inline-flex min-h-control w-full items-center justify-center rounded-control bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Create first business</Link></FlowCard>}
