"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Building2, CircleHelp, Droplets, Edit3, Landmark, Leaf, Recycle, ShieldCheck, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Card, ConfirmDialog, EmptyState, FormField, StatusBadge, formControlClassName } from "@/components/ui";
import { operatorBusinessRepository } from "@/data";
import { SubmitButton } from "@/features/auth/auth-controls";
import { OPERATOR_ID, OperationsLoading, PageHeading, actionClassName, secondaryActionClassName, titleCase } from "@/features/operator-operations";

export function OperatorProfileScreen(){const query=useQuery({queryKey:["operator-profile",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.profile(OPERATOR_ID)});if(query.isLoading)return <OperationsLoading/>;if(!query.data)return <EmptyState icon={UserRound} title="Profile unavailable" description="Your operator account could not be loaded."/>;const {user,operator,business,bank}=query.data;return <div><PageHeading eyebrow="Operator account" title={`${user.firstName} ${user.lastName}`} description={`${operator.legalName} trading as ${business.name}.`} action={<Link href="/operator/profile/edit" className={actionClassName}><Edit3 className="size-4"/>Edit profile</Link>}/><div className="mt-7 grid gap-5 lg:grid-cols-2"><Card className="p-6"><UserRound className="size-6 text-primary"/><h2 className="mt-4 text-xl font-semibold">Contact</h2><p className="mt-3 text-sm">{user.email}<br/>{user.phone}</p><div className="mt-4 flex gap-2"><StatusBadge tone={user.status==="ACTIVE"?"success":"danger"}>{titleCase(user.status)}</StatusBadge><StatusBadge tone={operator.status==="APPROVED"?"success":"warning"}>{titleCase(operator.status)}</StatusBadge></div></Card><Card className="p-6"><Building2 className="size-6 text-primary"/><h2 className="mt-4 text-xl font-semibold">{business.name}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{business.description}</p></Card></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Link href="/operator/profile/banking"><Card className="p-5 transition hover:border-primary"><Landmark className="size-5 text-primary"/><h2 className="mt-3 font-semibold">Banking</h2><p className="mt-1 text-sm text-muted-foreground">{bank?`${bank.bankName} •••• ${bank.accountNumberLast4}`:"Add payout account"}</p></Card></Link><Link href="/operator/account/terminate"><Card className="p-5 transition hover:border-danger"><ShieldCheck className="size-5 text-danger"/><h2 className="mt-3 font-semibold">Account controls</h2><p className="mt-1 text-sm text-muted-foreground">Review permanent account termination.</p></Card></Link></div></div>}

export function EditOperatorProfileScreen(){const router=useRouter();const client=useQueryClient();const query=useQuery({queryKey:["operator-profile",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.profile(OPERATOR_ID)});const mutation=useMutation({mutationFn:(input:Parameters<typeof operatorBusinessRepository.updateProfile>[1])=>operatorBusinessRepository.updateProfile(OPERATOR_ID,input),onSuccess:()=>{client.invalidateQueries({queryKey:["operator-profile"]});client.invalidateQueries({queryKey:["operator-dashboard"]});router.push("/operator/profile");}});if(query.isLoading)return <OperationsLoading/>;if(!query.data)return <EmptyState title="Profile unavailable" description="This profile cannot be edited."/>;const {user,business}=query.data;function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mutation.mutate({firstName:String(d.get("firstName")??""),lastName:String(d.get("lastName")??""),phone:String(d.get("phone")??""),businessName:String(d.get("businessName")??""),description:String(d.get("description")??"")});}return <div className="mx-auto max-w-2xl"><PageHeading eyebrow="Account details" title="Edit operator profile" description="Update the account contact and public business description."/><form onSubmit={submit} className="mt-7 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><div className="grid gap-5 sm:grid-cols-2"><FormField id="op-first" label="First name" required>{p=><input {...p} name="firstName" defaultValue={user.firstName} className={formControlClassName}/>}</FormField><FormField id="op-last" label="Last name" required>{p=><input {...p} name="lastName" defaultValue={user.lastName} className={formControlClassName}/>}</FormField></div><FormField id="op-phone" label="Phone" required>{p=><input {...p} name="phone" defaultValue={user.phone} className={formControlClassName}/>}</FormField><FormField id="op-business" label="Business name" required>{p=><input {...p} name="businessName" defaultValue={business.name} className={formControlClassName}/>}</FormField><FormField id="op-description" label="Business description" required>{p=><textarea {...p} name="description" defaultValue={business.description} rows={4} className={`${formControlClassName} resize-y`}/>}</FormField>{mutation.isError?<p role="alert" className="text-sm text-danger">{mutation.error.message}</p>:null}<SubmitButton pending={mutation.isPending}>Save changes</SubmitButton></form></div>}

export function BankingScreen(){const client=useQueryClient();const query=useQuery({queryKey:["operator-profile",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.profile(OPERATOR_ID)});const mutation=useMutation({mutationFn:(input:Parameters<typeof operatorBusinessRepository.updateBank>[1])=>operatorBusinessRepository.updateBank(OPERATOR_ID,input),onSuccess:()=>client.invalidateQueries({queryKey:["operator-profile"]})});if(query.isLoading)return <OperationsLoading/>;function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mutation.mutate({bankName:String(d.get("bankName")??""),accountName:String(d.get("accountName")??""),accountNumber:String(d.get("accountNumber")??"")});}return <div className="mx-auto max-w-2xl"><PageHeading eyebrow="Payout destination" title="Banking details" description="For safety, only the last four account digits are retained in this frontend prototype."/>{query.data?.bank?<Card className="mt-7 p-5"><div className="flex justify-between"><div><strong>{query.data.bank.bankName}</strong><p className="mt-1 text-sm text-muted-foreground">{query.data.bank.accountName} · •••• {query.data.bank.accountNumberLast4}</p></div><StatusBadge tone={query.data.bank.verified?"success":"warning"}>{query.data.bank.verified?"Verified":"Review pending"}</StatusBadge></div></Card>:null}<form onSubmit={submit} className="mt-5 space-y-5 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="bank-name" label="Bank name" required>{p=><input {...p} name="bankName" defaultValue={query.data?.bank?.bankName} className={formControlClassName}/>}</FormField><FormField id="account-name" label="Account name" required>{p=><input {...p} name="accountName" defaultValue={query.data?.bank?.accountName} className={formControlClassName}/>}</FormField><FormField id="account-number" label="Account number" required>{p=><input {...p} name="accountNumber" inputMode="numeric" placeholder="Enter full account number" className={formControlClassName}/>}</FormField>{mutation.isError?<p role="alert" className="text-sm text-danger">{mutation.error.message}</p>:null}{mutation.isSuccess?<p role="status" className="text-sm text-success">Banking details saved for review.</p>:null}<SubmitButton pending={mutation.isPending}>Save banking details</SubmitButton></form></div>}

export function TerminateAccountScreen(){const router=useRouter();const [phrase,setPhrase]=useState("");const [open,setOpen]=useState(false);const mutation=useMutation({mutationFn:()=>operatorBusinessRepository.terminate(OPERATOR_ID,phrase),onSuccess:()=>router.push("/")});return <div className="mx-auto max-w-xl"><PageHeading eyebrow="Permanent action" title="Terminate operator account" description="This closes the business and marks the operator login as deleted. It cannot be undone in the interface."/><Card className="mt-7 border-danger/25 p-6"><p className="text-sm leading-6 text-muted-foreground">Resolve orders and pending withdrawals before termination. Type <strong className="text-danger">TERMINATE</strong> to enable the final confirmation.</p><FormField id="terminate-phrase" label="Confirmation phrase">{p=><input {...p} value={phrase} onChange={e=>setPhrase(e.target.value)} className={`${formControlClassName} mt-5`}/>}</FormField><button type="button" disabled={phrase!=="TERMINATE"} onClick={()=>setOpen(true)} className="mt-5 min-h-control w-full rounded-control bg-danger px-4 text-sm font-semibold text-white disabled:bg-disabled disabled:text-disabled-foreground">Terminate account</button>{mutation.isError?<p role="alert" className="mt-3 text-sm text-danger">{mutation.error.message}</p>:null}</Card><ConfirmDialog open={open} onOpenChange={setOpen} title="Permanently terminate this account?" description="The business will close and this operator login will be deleted." confirmLabel="Terminate permanently" pending={mutation.isPending} tone="danger" onConfirm={()=>mutation.mutate()}/></div>}

export function OperatorSupportScreen(){const query=useQuery({queryKey:["operator-support"],queryFn:()=>operatorBusinessRepository.supportArticles()});return <div><PageHeading eyebrow="Help centre" title="Operator support" description="Guides for account, payment, fulfilment, and platform questions."/>{query.isLoading?<OperationsLoading/>:<div className="mt-7 grid gap-4 md:grid-cols-2">{query.data?.map(article=><Link key={article.id} href={`/operator/support/${article.id}`}><Card className="h-full p-5 transition hover:border-primary"><CircleHelp className="size-5 text-primary"/><p className="mt-4 text-xs font-semibold text-primary">{titleCase(article.category)}</p><h2 className="mt-2 font-semibold">{article.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{article.summary}</p></Card></Link>)}</div>}</div>}

export function OperatorSupportArticleScreen({articleId}:{articleId:string}){const query=useQuery({queryKey:["operator-support",articleId],queryFn:()=>operatorBusinessRepository.findSupportArticle(articleId)});if(query.isLoading)return <OperationsLoading/>;if(!query.data)return <EmptyState title="Article not found" description="This help article is unavailable."/>;return <article className="mx-auto max-w-3xl"><Link href="/operator/support" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/>Support</Link><PageHeading eyebrow={titleCase(query.data.category)} title={query.data.title} description={query.data.summary}/><Card className="mt-7 p-7"><p className="leading-8 text-muted-foreground">{query.data.body}</p></Card></article>}

export function OperatorAboutScreen(){return <div><PageHeading eyebrow="About AquaLoop" title="Local water, circular operations" description="AquaLoop helps approved operators sell refills, manage reusable containers, and complete secure handovers."/><section className="mt-7 rounded-panel bg-aqua-950 p-8 text-white"><Droplets className="size-10 text-aqua-200"/><h2 className="mt-5 text-3xl font-semibold">Operate a dependable refill loop</h2><p className="mt-3 max-w-2xl leading-7 text-aqua-100">Orders, stock, payments, delivery, and confirmation codes share one operational record.</p></section><div className="mt-5 grid gap-4 sm:grid-cols-3">{[[Recycle,"Reusable inventory"],[ShieldCheck,"Verified handovers"],[Leaf,"Local impact"]].map(([Icon,label])=><Card key={String(label)} className="p-5"><Icon className="size-5 text-primary"/><h2 className="mt-3 font-semibold">{String(label)}</h2></Card>)}</div></div>}

export function OperatorTermsScreen(){const sections=[["Operating responsibilities","Keep stock, opening status, fulfilment progress, prices, and customer handovers accurate."],["Payments and settlement","Earnings and withdrawals in this frontend are simulated. Production settlement rules require legal and payment-provider review."],["Reusable containers","Record empty returns only at genuine handover and maintain accurate filled, empty, reserved, and damaged counts."],["Account controls","AquaLoop may suspend an operator or business that fails verification or platform requirements."]];return <article className="mx-auto max-w-3xl"><PageHeading eyebrow="Operator information" title="Terms of service" description="The working operator terms represented by this prototype."/><Card className="mt-7 p-7"><p className="rounded-control bg-warning-soft p-4 text-sm text-warning">Prototype copy — legal review is required before production use.</p><div className="mt-7 space-y-7">{sections.map(([title,body])=><section key={title}><h2 className="text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">{body}</p></section>)}</div></Card><nav className="mt-5 flex flex-wrap gap-3"><Link href="/operator/about" className={secondaryActionClassName}>About AquaLoop</Link><Link href="/operator/support" className={secondaryActionClassName}>Support <ArrowRight className="size-4"/></Link></nav></article>}
