"use client";

import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, MessageSquareText, Star, Truck } from "lucide-react";
import Link from "next/link";

import { Card, EmptyState, StatusBadge, Timeline } from "@/components/ui";
import { operatorBusinessRepository } from "@/data";
import { OPERATOR_ID, OperationsLoading, PageHeading, formatDate, statusTone, titleCase } from "@/features/operator-operations";
import { formatMoney } from "@/lib/money";

export function DeliveriesScreen(){const query=useQuery({queryKey:["operator-deliveries",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.deliveries(OPERATOR_ID)});return <div><PageHeading eyebrow="Fulfilment" title="Deliveries" description="See assignments, customer destinations, ETAs, and completed drop-offs."/>{query.isLoading?<OperationsLoading/>:<div className="mt-7 space-y-4">{query.data?.map(({delivery,order,customer})=><Link key={delivery.id} href={`/operator/deliveries/${delivery.id}`} className="block"><Card className="flex flex-col justify-between gap-4 p-5 sm:flex-row"><div><div className="flex gap-2"><strong>{order?.orderNumber??delivery.orderId}</strong><StatusBadge size="sm" tone={statusTone(delivery.status)}>{titleCase(delivery.status)}</StatusBadge></div><p className="mt-2 text-sm text-muted-foreground">{customer?`${customer.firstName} ${customer.lastName}`:"Customer"} · {delivery.assignedToName??"Unassigned"}</p></div><span className="text-sm text-muted-foreground">{delivery.etaMinutes?`${delivery.etaMinutes} min ETA`:formatDate(delivery.createdAt)}</span></Card></Link>)}</div>}</div>}

export function DeliveryDetailScreen({deliveryId}:{deliveryId:string}){const query=useQuery({queryKey:["operator-delivery",OPERATOR_ID,deliveryId],queryFn:()=>operatorBusinessRepository.findDelivery(OPERATOR_ID,deliveryId)});if(query.isLoading)return <OperationsLoading/>;if(!query.data)return <EmptyState icon={Truck} title="Delivery not found" description="This delivery does not belong to your business."/>;const {delivery,order,customer}=query.data;const stages=["ASSIGNED","PICKED_UP","EN_ROUTE","ARRIVED","COMPLETED"];const current=Math.max(0,stages.indexOf(delivery.status));return <div><Link href="/operator/deliveries" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/>Deliveries</Link><PageHeading eyebrow={order?.orderNumber??delivery.id} title={customer?`${customer.firstName} ${customer.lastName}`:"Customer delivery"} description={delivery.assignedToName?`Assigned to ${delivery.assignedToName} · ${delivery.assignedToPhone}`:"Awaiting a delivery assignment."}/><div className="mt-7 grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="font-semibold">Delivery progress</h2><Timeline className="mt-5" items={stages.map((stage,index)=>({id:stage,title:titleCase(stage),state:index<current?"complete":index===current?"current":"upcoming"}))}/></Card><Card className="p-6"><h2 className="font-semibold">Order details</h2><p className="mt-4 text-3xl font-semibold">{order?formatMoney(order.total):"—"}</p><p className="mt-2 text-sm text-muted-foreground">Created {formatDate(delivery.createdAt,true)}</p>{delivery.etaMinutes?<p className="mt-5 rounded-control bg-primary-soft p-4 text-sm font-semibold text-primary">Current ETA: {delivery.etaMinutes} minutes</p>:null}</Card></div></div>}

export function OperatorHistoryScreen(){const query=useQuery({queryKey:["operator-history",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.history(OPERATOR_ID)});return <div><PageHeading eyebrow="Business records" title="Order history" description="Completed, cancelled, and refunded orders retained for your records."/>{query.isLoading?<OperationsLoading/>:query.data?.length?<div className="mt-7 space-y-3">{query.data.map(order=><Link key={order.id} href={`/operator/orders/${order.id}`} className="block"><Card className="flex justify-between gap-4 p-5"><div><strong>{order.orderNumber}</strong><p className="mt-1 text-sm text-muted-foreground">Updated {formatDate(order.updatedAt,true)}</p></div><div className="text-right"><StatusBadge size="sm" tone={statusTone(order.status)}>{titleCase(order.status)}</StatusBadge><p className="mt-2 font-semibold">{formatMoney(order.total)}</p></div></Card></Link>)}</div>:<EmptyState className="mt-7" title="No historical orders" description="Completed and cancelled orders will appear here."/>}</div>}

export function ReviewsScreen(){const query=useQuery({queryKey:["operator-reviews",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.reviews(OPERATOR_ID)});return <div><PageHeading eyebrow="Customer feedback" title="Reviews" description="Read the ratings customers leave after completed orders."/>{query.isLoading?<OperationsLoading/>:<div className="mt-7 space-y-4">{query.data?.map(({review,customer})=><Link key={review.id} href={`/operator/reviews/${review.id}`} className="block"><Card className="p-5"><div className="flex justify-between gap-3"><strong>{customer?`${customer.firstName} ${customer.lastName}`:"Customer"}</strong><span className="inline-flex items-center gap-1 font-semibold text-warning"><Star className="size-4 fill-warning"/>{review.rating}</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{review.body}</p><p className="mt-3 text-xs text-muted-foreground">{formatDate(review.createdAt)}</p></Card></Link>)}</div>}</div>}

export function ReviewDetailScreen({reviewId}:{reviewId:string}){const query=useQuery({queryKey:["operator-review",OPERATOR_ID,reviewId],queryFn:()=>operatorBusinessRepository.findReview(OPERATOR_ID,reviewId)});if(query.isLoading)return <OperationsLoading/>;if(!query.data)return <EmptyState icon={MessageSquareText} title="Review not found" description="This review does not belong to your business."/>;const {review,customer,order}=query.data;return <div className="mx-auto max-w-2xl"><Link href="/operator/reviews" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/>Reviews</Link><PageHeading eyebrow={order?.orderNumber??"Verified customer review"} title={`${review.rating} out of 5`} description={`From ${customer?`${customer.firstName} ${customer.lastName}`:"a customer"} on ${formatDate(review.createdAt)}.`}/><Card className="mt-7 p-7"><div className="flex gap-1">{[1,2,3,4,5].map(value=><Star key={value} className={`size-6 ${value<=review.rating?"fill-warning text-warning":"text-border-strong"}`}/>)}</div><blockquote className="mt-6 text-lg leading-8">“{review.body}”</blockquote></Card></div>}
