"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CheckCircle2, CreditCard, Landmark, WalletCards } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { Card, EmptyState, FormField, StatusBadge, formControlClassName } from "@/components/ui";
import { operatorBusinessRepository } from "@/data";
import { SubmitButton } from "@/features/auth/auth-controls";
import { OPERATOR_ID, OperationsLoading, PageHeading, actionClassName, formatDate, secondaryActionClassName, statusTone, titleCase } from "@/features/operator-operations";
import { formatMoney } from "@/lib/money";

export function EarningsScreen({ history = false }: { history?: boolean }) {
  const query=useQuery({queryKey:["operator-finance",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.finance(OPERATOR_ID)});
  if(query.isLoading)return <OperationsLoading/>; if(!query.data)return <EmptyState title="Earnings unavailable" description="Your operator wallet could not be loaded."/>;
  const entries=history?query.data.entries:query.data.entries.slice(0,5); const earned=query.data.entries.filter(e=>e.direction==="CREDIT").reduce((s,e)=>s+e.amount,0);
  return <div><PageHeading eyebrow="Operator wallet" title={history?"Earnings history":"Earnings"} description="A clear ledger of order earnings, plan charges, and withdrawals." action={!history?<Link href="/operator/withdrawals/new" className={actionClassName}>Withdraw funds</Link>:undefined}/><div className="mt-7 grid gap-4 sm:grid-cols-2"><Card className="p-5"><WalletCards className="size-5 text-primary"/><p className="mt-4 text-3xl font-semibold">{formatMoney(query.data.wallet.cachedBalance)}</p><p className="text-sm text-muted-foreground">Available balance</p></Card><Card className="p-5"><Landmark className="size-5 text-primary"/><p className="mt-4 text-3xl font-semibold">{formatMoney(earned)}</p><p className="text-sm text-muted-foreground">Recorded earnings</p></Card></div><div className="mt-7 flex justify-between"><h2 className="text-heading-2 font-semibold">{history?"All activity":"Recent activity"}</h2>{!history?<Link href="/operator/earnings/history" className="text-sm font-semibold text-primary">View history</Link>:null}</div><div className="mt-4 space-y-3">{entries.map(entry=><Card key={entry.id} className="flex justify-between gap-4 p-5"><div><strong>{entry.description}</strong><p className="mt-1 text-sm text-muted-foreground">{titleCase(entry.type)} · {formatDate(entry.createdAt,true)}</p></div><strong className={entry.direction==="CREDIT"?"text-success":"text-danger"}>{entry.direction==="CREDIT"?"+":"−"}{formatMoney(entry.amount)}</strong></Card>)}</div></div>;
}

export function PlansScreen(){const query=useQuery({queryKey:["operator-plans",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.plans(OPERATOR_ID)});return <div><PageHeading eyebrow="Business subscription" title="Plans" description="Choose the fee structure and analytics allowance that fits your operation."/>{query.isLoading?<OperationsLoading/>:<div className="mt-7 grid gap-4 lg:grid-cols-3">{query.data?.plans.map(plan=><Card key={plan.id} className="flex flex-col p-6"><div className="flex justify-between gap-2"><h2 className="text-xl font-semibold">{titleCase(plan.name)}</h2>{query.data.current?.id===plan.id?<StatusBadge tone="success">Current</StatusBadge>:null}</div><p className="mt-4 text-3xl font-semibold">{formatMoney(plan.monthlyFee)}<span className="text-sm font-normal text-muted-foreground"> / month</span></p><ul className="mt-5 flex-1 space-y-2 text-sm text-muted-foreground"><li>{plan.settlementFeePercent}% settlement fee</li><li>Up to {plan.maxBusinesses} businesses</li><li>{plan.analyticsRetentionDays} days analytics</li></ul><Link href={`/operator/plans/${plan.id}`} className={`${query.data.current?.id===plan.id?secondaryActionClassName:actionClassName} mt-6`}>View plan</Link></Card>)}</div>}</div>}

export function PlanDetailScreen({planId}:{planId:string}){const query=useQuery({queryKey:["operator-plan",OPERATOR_ID,planId],queryFn:()=>operatorBusinessRepository.findPlan(OPERATOR_ID,planId)});if(query.isLoading)return <OperationsLoading/>;if(!query.data)return <EmptyState title="Plan not found" description="This subscription is unavailable."/>;const {plan,current}=query.data;return <div className="mx-auto max-w-2xl"><Link href="/operator/plans" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/>Plans</Link><PageHeading eyebrow="Subscription option" title={titleCase(plan.name)} description={`${plan.analyticsRetentionDays} days of analytics with a ${plan.settlementFeePercent}% settlement fee.`}/><Card className="mt-7 p-6"><p className="text-4xl font-semibold">{formatMoney(plan.monthlyFee)}<span className="text-sm font-normal text-muted-foreground"> / month</span></p><div className="mt-5 grid gap-3 sm:grid-cols-3"><p className="rounded-control bg-surface-muted p-4 text-sm"><strong>{plan.maxBusinesses}</strong><br/>businesses</p><p className="rounded-control bg-surface-muted p-4 text-sm"><strong>{plan.analyticsRetentionDays}</strong><br/>analytics days</p><p className="rounded-control bg-surface-muted p-4 text-sm"><strong>{plan.settlementFeePercent}%</strong><br/>settlement fee</p></div>{current?.id===plan.id?<StatusBadge className="mt-6" tone="success">Current plan</StatusBadge>:<Link href={`/operator/plans/${plan.id}/pay`} className={`${actionClassName} mt-6 w-full`}>Choose this plan <ArrowRight className="size-4"/></Link>}</Card></div>}

export function PlanPayScreen({planId}:{planId:string}){const router=useRouter();const client=useQueryClient();const query=useQuery({queryKey:["operator-plan",OPERATOR_ID,planId],queryFn:()=>operatorBusinessRepository.findPlan(OPERATOR_ID,planId)});const mutation=useMutation({mutationFn:()=>operatorBusinessRepository.selectPlan(OPERATOR_ID,planId),onSuccess:(result)=>{client.invalidateQueries({queryKey:["operator-plan"]});client.invalidateQueries({queryKey:["operator-plans"]});client.invalidateQueries({queryKey:["operator-finance"]});router.push(`/operator/plans/${planId}/success?reference=${result.reference}`);}});if(query.isLoading)return <OperationsLoading/>;if(!query.data)return <EmptyState title="Plan unavailable" description="Return to plans to choose another option."/>;return <div className="mx-auto max-w-xl"><PageHeading eyebrow="Confirm subscription" title={`Switch to ${titleCase(query.data.plan.name)}`} description="The monthly fee will be deducted from your operator earnings balance."/><Card className="mt-7 p-6"><CreditCard className="size-6 text-primary"/><div className="mt-5 flex justify-between"><span>Due now</span><strong>{formatMoney(query.data.plan.monthlyFee)}</strong></div></Card><button type="button" onClick={()=>mutation.mutate()} disabled={mutation.isPending||query.data.current?.id===planId} className={`${actionClassName} mt-5 w-full`}>{mutation.isPending?"Processing…":"Confirm plan"}</button>{mutation.isError?<p role="alert" className="mt-3 text-sm text-danger">{mutation.error.message}</p>:null}</div>}

export function PlanSuccessScreen({reference}:{reference?:string}){return <div className="mx-auto max-w-xl text-center"><CheckCircle2 className="mx-auto size-16 text-success"/><p className="mt-5 text-sm font-semibold text-success">{reference??"Subscription updated"}</p><h1 className="mt-2 text-heading-1 font-semibold">Plan activated</h1><p className="mt-3 text-muted-foreground">Your operator limits and settlement fee are now updated.</p><Link href="/operator/plans" className={`${actionClassName} mt-7`}>View plans</Link></div>}

export function WithdrawalsScreen(){const query=useQuery({queryKey:["operator-withdrawals",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.withdrawals(OPERATOR_ID)});return <div><PageHeading eyebrow="Payouts" title="Withdrawals" description="Request transfers and follow each payout through review and settlement." action={<Link href="/operator/withdrawals/new" className={actionClassName}>New withdrawal</Link>}/>{query.isLoading?<OperationsLoading/>:<><Card className="mt-7 p-5"><p className="text-sm text-muted-foreground">Available balance</p><p className="mt-2 text-3xl font-semibold">{formatMoney(query.data?.wallet.cachedBalance??0)}</p></Card><div className="mt-5 space-y-3">{query.data?.rows.map(row=><Link key={row.id} href={`/operator/withdrawals/${row.id}`} className="block"><Card className="flex justify-between gap-4 p-5"><div><strong>{formatMoney(row.amount)}</strong><p className="mt-1 text-sm text-muted-foreground">Requested {formatDate(row.requestedAt,true)}</p></div><StatusBadge tone={statusTone(row.status)}>{titleCase(row.status)}</StatusBadge></Card></Link>)}</div></>}</div>}

export function NewWithdrawalScreen(){const router=useRouter();const client=useQueryClient();const query=useQuery({queryKey:["operator-withdrawals",OPERATOR_ID],queryFn:()=>operatorBusinessRepository.withdrawals(OPERATOR_ID)});const [error,setError]=useState("");const mutation=useMutation({mutationFn:(amount:number)=>operatorBusinessRepository.requestWithdrawal(OPERATOR_ID,amount),onSuccess:row=>{client.invalidateQueries({queryKey:["operator-withdrawals"]});client.invalidateQueries({queryKey:["operator-finance"]});router.push(`/operator/withdrawals/${row.id}`);}});function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const pounds=Number(new FormData(e.currentTarget).get("amount"));if(!Number.isFinite(pounds)||pounds<=0){setError("Enter a valid amount.");return}setError("");mutation.mutate(Math.round(pounds*100));}return <div className="mx-auto max-w-xl"><PageHeading eyebrow="Payout request" title="New withdrawal" description={`Available balance: ${formatMoney(query.data?.wallet.cachedBalance??0)}. Pending requests reserve funds immediately.`}/><form onSubmit={submit} className="mt-7 rounded-panel border border-border bg-surface p-6 shadow-card"><FormField id="withdrawal-amount" label="Amount in GBP" error={error} required disabled={mutation.isPending}>{props=><input {...props} name="amount" type="number" min="1" step="0.01" className={formControlClassName}/>}</FormField>{mutation.isError?<p role="alert" className="mt-4 text-sm text-danger">{mutation.error.message}</p>:null}<SubmitButton pending={mutation.isPending} className="mt-5"><Landmark className="size-4"/>Request withdrawal</SubmitButton></form></div>}

export function WithdrawalDetailScreen({withdrawalId}:{withdrawalId:string}){const query=useQuery({queryKey:["operator-withdrawal",OPERATOR_ID,withdrawalId],queryFn:()=>operatorBusinessRepository.findWithdrawal(OPERATOR_ID,withdrawalId)});if(query.isLoading)return <OperationsLoading/>;if(!query.data)return <EmptyState title="Withdrawal not found" description="This payout request does not belong to your account."/>;return <div className="mx-auto max-w-xl"><PageHeading eyebrow={query.data.id} title={formatMoney(query.data.amount)} description={`Requested ${formatDate(query.data.requestedAt,true)}`}/><Card className="mt-7 p-6"><div className="flex justify-between"><span>Status</span><StatusBadge tone={statusTone(query.data.status)}>{titleCase(query.data.status)}</StatusBadge></div><p className="mt-5 text-sm leading-6 text-muted-foreground">Pending withdrawals have already been reserved from your available balance. Paid requests include their final processing date.</p>{query.data.processedAt?<p className="mt-4 text-sm">Processed {formatDate(query.data.processedAt,true)}</p>:null}</Card></div>}
